### ISSUE TITLE
Disable only touchscreen for battery save?

### ISSUE THREAD

**Issue by piticrobert** [Xiashangning/BigSurface#102]
Hello, I have a Surface Laptop Go 1, and I want to know if is a way to disable only the touchscreen because I don't use it, and I want to save some battery life?

**Comment by piticrobert** [comment]
up

**Comment by Xiashangning** [comment]
Sure, you can just delete `SurfaceManagementEngine` item in Info.plist-IOPersonalities so the touchscreen won't be loaded.
