### ISSUE TITLE
Bluetooth USB dongle not loading / conflict with Wifi Kext?

### ISSUE THREAD

**Issue by ciuhc** [Xiashangning/BigSurface#103]
I'm struggling to get a Broadcom based usb bluetooth dongle to work in my SurfaceBook 3. The dongle is natively supported by MacOS and should just fly.

I tried using XCode tools Bluetooth Explorer -> Host Controller Selector but it doesn't load at all into the list. Meanwhile it lives happily in System report... Anyone having similar issues?

**Comment by Xiashangning** [comment]
I am sorry but I think this is an unrelated issue. Maybe post it on some forum?
