### ISSUE TITLE
The Fix of KP on Ventura Breaks Touchpad Support in macOS Monterey

### ISSUE THREAD

**Issue by misaka-20002** [Xiashangning/BigSurface#104]
Title
As I tried to upgrade to Ventura, I updated my kexts and found that problem(I'm on 12.0.1)
After many tries, I found that the versions before v6.4 can work properly but after can't.
Should add an version check before applying the kp fix?

**Comment by Xiashangning** [comment]
I will have a look at it. Normally that is impossible since the lowest macOS version set when compiling is Mojave.
Have you updated the loading kext? Because there is one more plugin kext to load for version 6.4
