### ISSUE TITLE
USB C charging stopped working?

### ISSUE THREAD

**Issue by ciuhc** [Xiashangning/BigSurface#105]
It used to work but now seems like there's issues with handshake. Anyone else experience this?

**Comment by Xiashangning** [comment]
For me no, and this also has nothing to do with BigSurface.kext.
I think the only possible problem is USB mapping issues. But anyway I will leave it here for a couple of days to see if others have the same problem

**Comment by jlempen** [comment]
Well, on my i5 SP7 with BigSurface v6.5, if I boot with the USB-C power adapter plugged in, the battery icon shows the little lightning bolt as if it was charging, but the battery is actually discharging. If I unplug and replug the USB-C power adapter, it starts charging again.

BTW, I do not use [badstorm's EFI for the SP7](https://github.com/badstorm/surface-pro-7-opencore), but [Xiashangning's EFI](https://github.com/Xiashangning/SurfacePro7Opencore), updated to OpenCore 0.9.2 and all the kexts updated as well.

**Comment by Rainringgoaway** [comment]
Might be surface UEFIframework update.

**Comment by ciuhc** [comment]
I was playing around a bit and concluded there is some handshake issue when charging starts - OSX keeps showing the icon change between charging and not charging every 5 seconds...

**Comment by c95599** [comment]
确实，usb-c插着充电线，显示充电状态，但是电量是往下掉的，还有，按一下电源键，不能熄屏，长按电源键，跳出关机啥的菜单，原先可以按电源键熄屏的，但是合上键盘盖，能熄屏，做的很好了，就提交一下这些问题

**Comment by Rainringgoaway** [comment]
最近的surface驱动更新修复了c口充电问题，可以去win系统里更新下驱动再尝试充电。

**Comment by jlempen** [comment]
> 最近的surface驱动更新修复了c口充电问题，可以去win系统里更新下驱动再尝试充电。

```
Translation: The latest Surface driver update has fixed the C-port charging problem. You can update the driver in the Windows system and try charging again.
```
I think we can close this now.
