### ISSUE TITLE
[Questions] the details about other kexts needed & appropriate config.plist for Ventura on SB3? 

### ISSUE THREAD

**Issue by ryanlo713** [Xiashangning/BigSurface#106]
I'm not sure what kexts to install in addition to BigSurface.

**Comment by Xiashangning** [comment]
Sorry, but here is the place where people report issues with BigSurface.kext.
I would suggest you search it on google/reddit or just on github to see if there are OC configs for SB3 (configs for SL3 maybe also work for SB3, you can use that as a start point)
