### ISSUE TITLE
KP when hot plugging keyboard/turning off/rebooting in Ventura

### ISSUE THREAD

**Issue by SoSlowA** [Xiashangning/BigSurface#110]
ENG:
In Ventura, KP happens when hot plugging keyboard
Meanwhile, when turning off the computer or rebooting, the computer will reboot and show "Your computer restarted because of a problem". I think it is because when disconnecting the keyboard, KP happens as hot plugging.
Release v6.4 says that "Fixed KP on Ventura for TypeCover.", but when using v6.5 this problem still happens. I'm wondering.
P.S. My Kexts of BigSurface include following:(PlugIns/)VoodooGPIO.kext, (PlugIns/)VoodooSerial.kext, (PlugIns/)VoodooInput.kext, BigSurface.kext, (PlugIns/)BigSurfaceHIDDriver.kext, (PlugIns/)VoodooI2CServices.kext
P.S.2 Hope you to read CN because the EN edition may not express properly.
CN:
在Mac OS Ventura中，仍存在热插拔键盘后产生KP重启的状况
同时在通过系统进行关机/重启时，电脑会直接重启，OC中选择Mac进入后显示“因问题重启”五国语言，估计为断开键盘连接时导致的热插拔键盘KP
6.4 Release中说已修复“KP on Ventura for TypeCover”，但是目前使用6.5时仍出现问题，不知为什么
另：BigSurface相关Kext包括（按照说明顺序）：(PlugIns/)VoodooGPIO.kext，(PlugIns/)VoodooSerial.kext，(PlugIns/)VoodooInput.kext，BigSurface.kext，(PlugIns/)BigSurfaceHIDDriver.kext，(PlugIns/)VoodooI2CServices.kext

**Comment by jlempen** [comment]
@SoSlowA 

> P.S. My Kexts of BigSurface include following:(PlugIns/)VoodooGPIO.kext, (PlugIns/)VoodooSerial.kext, (PlugIns/)VoodooInput.kext, BigSurface.kext, (PlugIns/)BigSurfaceHIDDriver.kext, (PlugIns/)VoodooI2CServices.kext

Starting with `BigSurface` v6.4, the plugin `BigSurfaceHIDDriver.kext` **_replaces_** `VoodooI2CServices.kext` and the order of the kexts in your `config.plist` file is different as well.

![image](https://github.com/user-attachments/assets/6d50107e-7839-48cf-867b-e91e90adcd04)

Please re-read the [install instructions](https://github.com/Xiashangning/BigSurface?tab=readme-ov-file#how-to-install) and make the required changes in your EFI folder.
