### ISSUE TITLE
surface laptop 3 触摸板断触

### ISSUE THREAD

**Issue by kevin-Curry** [Xiashangning/BigSurface#112]
使用最新6.5bigsurface和1.4 IPTSDaemon
surface laptop 3 Ventura Monterey断触

**Comment by szsong** [comment]
Same here. 遇到一样的情况。
Downgraded to release version 6.3 and the issue resolved.
降级到 release 6.3 以后工作正常。

**Comment by kevin-Curry** [comment]
> Same here. 遇到一样的情况。 Downgraded to release version 6.3 and the issue resolved. 降级到 release 6.3 以后工作正常。

如何使用命令安装fmt9.0？

**Comment by szsong** [comment]
> > Same here. 遇到一样的情况。 Downgraded to release version 6.3 and the issue resolved. 降级到 release 6.3 以后工作正常。
> 
> 如何使用命令安装fmt9.0？

??? why this question?

**Comment by jc-bao** [comment]
Downgrade to 6.3 doesn't resolve the issue for me 😢 I am using SL3 15inch. Does anybody have other solutions? Could this related to the firmware version?

**Comment by jlempen** [comment]
Fixed by https://github.com/Xiashangning/BigSurface/issues/79#issuecomment-2208484390
