### ISSUE TITLE
loptop3 15寸 的设备ID：0x34ED 开机无法正常启动 

### ISSUE THREAD

**Issue by xixi160323** [Xiashangning/BigSurface#117]
<img width="662" alt="截屏2024-01-13 13 20 11" src="https://github.com/Xiashangning/BigSurface/assets/156495956/b202540a-9bbb-43dd-ae53-ed624aca31e2">
希望老师有时间能够更新对此设备的支持

**Comment by xixi160323** [comment]
![Uploading IMG_5976.jpeg…]()

**Comment by xixi160323** [comment]
![IMG_5976](https://github.com/Xiashangning/BigSurface/assets/156495956/68ad640f-26ee-401e-8079-3aeebb6ffbf2)

**Comment by jlempen** [comment]
@xixi160323 

The `Surface Laptop 3` works with `BigSurface` v6.3 and newer, even if the trackpad is a bit choppy. But there's a fix: https://github.com/Xiashangning/BigSurface/issues/79#issuecomment-2208484390 

Regarding your boot issues, this has nothing to do with `BigSurface`. Please read the [Dortania OpenCore guide](https://dortania.github.io/OpenCore-Install-Guide/) to make your own EFI for your SL3.
