### ISSUE TITLE
键盘热插拔

### ISSUE THREAD

**Issue by aTan20170106** [Xiashangning/BigSurface#119]
你好，请能讲一下键盘热插拔的原理吗？手上的yoga duet 2020 键盘分离后，接上触控板是用不了。想借鉴来使用

**Comment by jlempen** [comment]
@aTan20170106 

Your Yoga Duet 2020's keyboard cover is USB and should work out of the box with [VoodooI2C / VoodooI2CHID](https://github.com/VoodooI2C/VoodooI2C), as USB support was added in v2.9.

`BigSurface` is only compatible with Microsoft Surface devices.
