### ISSUE TITLE
TypeCover not working on Monterey

### ISSUE THREAD

**Issue by lutzmor** [Xiashangning/BigSurface#12]
Hey all,

I'm stuck currently ( I installed Monterey on my surface pro 7 ) without a lot of problems. Everything is working beside the type cover ( wasn't working the last time I tried Big Sur a while back ).

I can see the type cover in the System Information below USB but nor the keyboard or the trackpad work in anyway :(.

I uploaded my EFI folder to https://github.com/lutzmor/surface7 maybe someone sees something I overlooked or I messed up completely.

Thanks in advance :)

**Comment by Xiashangning** [comment]
Well, do you have BigSurface and VoodooI2C loaded at the same time ?

**Comment by Xiashangning** [comment]
Solved in next release

**Comment by therealjbenam** [comment]
> Solved in next release

Any ETA for the next release? Really looking forward to Monterey, but I can't afford risk losing the Type Cover :(

**Comment by Xiashangning** [comment]
You can check https://github.com/Xiashangning/BigSurface/issues/5#issuecomment-957896644 for temporary fix
As for the new release, well, I am afraid it will not be released very soon. I am currently busy debuging and testing the battery driver on serval machines(SP7, SP6), bumping up a version for such a small fix seems unnecessary to me.

**Comment by therealjbenam** [comment]
> You can check [#5 (comment)](https://github.com/Xiashangning/BigSurface/issues/5#issuecomment-957896644) for temporary fix As for the new release, well, I am afraid it will not be released very soon. I am currently busy debuging and testing the battery driver on serval machines(SP7, SP6), bumping up a version for such a small fix seems unnecessary to me.

Cool, thanks, looks like I have missed that comment - I can now finally upgrade to Monterey!

If you need any help testing the battery driver, my SP6 is at your service.
