### ISSUE TITLE
A name suggestion 

### ISSUE THREAD

**Issue by Gogoseit2020** [Xiashangning/BigSurface#120]
While BigSurface is a catchy name consider 
Hack OS big Sur
SurfOS 
or BigSurfOS (damn I think these are worse...)

**Comment by jlempen** [comment]
@Gogoseit2020 

While your naming ideas are quite funny indeed, please consider that `BigSurface` is not an operating system, so the `OS` part of the name isn't relevant here.

Another thing to consider is that most people who run macOS on their Surface device rely on `BigSurface` to get their trackpad/keyboard/touchscreen/battery working and know this kext by the name `BigSurface`, so I wouldn't change it as it would only confuse the users.

But if I had to suggest a better name for this kext, I would say `MacSurface` 😃
