### ISSUE TITLE
Will Legacy Keyboards (SP3 And Older) Be Supported? (QUESTION)

### ISSUE THREAD

**Issue by beatrixzy** [Xiashangning/BigSurface#123]
Hi There, I Got My SP3 Not To Long Ago And Thought "I Want To Hackintosh It". So I Tried Yesterday, I Managed To Get A Working EFI That Reverse Engineered The Drivers For This Machine And Repo. However, Since My Keyboard Is A 16xx Model It Isn't Supported On macOS. (The EFI I'm Using Is https://github.com/balopez83/Surface_Pro_3_Hackintosh ) The Owner Of That Repo Said I Should Ask You Guys To See If  Support Will Be Added.

**Comment by jlempen** [comment]
@Basil-giting 

Unlike its younger Surface siblings, the `Surface Pro 3` does not need the `BigSurface` kext, it is pretty much an ordinary laptop. The Type Cover is USB and should work out of the box with [VoodooI2C / VoodooI2CHID](https://github.com/VoodooI2C/VoodooI2C), as USB support was added in v2.9.
