### ISSUE TITLE
Random auto-click the screen after fold the keyboard/sleep for a while and login back

### ISSUE THREAD

**Issue by LvxlongSir** [Xiashangning/BigSurface#125]
Every a few mins the cursor move to certain place of top screen. 1/3 top or 2/3 top position, window tiltle area.
It's random and can only reproduce after sleep and login back. Maybe need fold the keyboad and screen and wait for a certain time.

Restart will temporarily fix the issue. But once sleep and login back. This reoccurs.

**Comment by jlempen** [comment]
@LvxlongSir, on which device do you have this issue? And with which version of `BigSurface` and `IPTSDaemon`? Which version of macOS?

**Comment by jlempen** [comment]
Closing due to no response

**Comment by ThePilger** [comment]
i have the same problem on surface pro 6
