### ISSUE TITLE
Is this project still supported?

### ISSUE THREAD

**Issue by legatimatteo** [Xiashangning/BigSurface#129]
Hi, the last release was published on Feb 26 2023 but some files were changed a few months ago so I wanted to know if the project is still actively supported or if it has been discontinued.

I am using a surface pro 7.
Thanks

**Comment by Xiashangning** [comment]
Hi, yes (though might not be "actively").
Most critical functions are already implemented. Future updates would be bug fixes.
If your device is SP7, there should be no problem/bug using this kext.
