### ISSUE TITLE
Regarding the support issues of Surface Pro M3 in the 10.14.6 system.

### ISSUE THREAD

**Issue by 418035875** [Xiashangning/BigSurface#130]
My Surface Pro M3 is still noticeably laggy when installed with 10.15.7. It runs much better with 10.14.6. However, the touchpad doesn't work properly and is recognized as a mouse instead. All gestures are missing. I would like to know if it's possible to make Big Surface support 10.14.6.

**Comment by 418035875** [comment]
I can't do without the support of the trackpad, I finally chose to use 10.15.7. Even if it runs a bit more sluggishly than 10.14.6.

**Comment by jlempen** [comment]
It just wouldn't make sense to spend time on adding support for a six years old version of macOS for which Apple dropped support in October 2021, sorry.
