### ISSUE TITLE
[Question] Is there any other kexts that needs to be installed/removed?

### ISSUE THREAD

**Issue by Helloyunho** [Xiashangning/BigSurface#14]
I'm trying to install this kext to my surface. But the kernel panics due to the kexts not compatible with each other.
Is there any other kexts needs to be installed/removed?

**Comment by Xiashangning** [comment]
Well, you have to show me your config or I cannot tell what is wrond, at least a screenshot of Kext loaded in config.plist

**Comment by Xiashangning** [comment]
Mostly, VoodooI2C series should be removed

**Comment by Helloyunho** [comment]
> Well, you have to show me your config or I cannot tell what is wrong, at least a screenshot of Kext loaded in config.plist

Here's what I've installed right now:
![kexts](https://user-images.githubusercontent.com/10192625/141126461-65b99456-f5ec-4d89-83ca-1a088cc8fb62.png)

**Comment by Xiashangning** [comment]
Remove VoodooI2C series and move BigSurface.kext under its plugins
Also, you won't need BrightnessKeys.kext

**Comment by Xiashangning** [comment]
That's it, try again

**Comment by Helloyunho** [comment]
Nice it booted now
But now the type cover doesn't work...
Do I have to map the USB with the type cover port enabled? (I disabled it because I thought BigSurface will do it by it's own)

**Comment by Xiashangning** [comment]
Does yout keyboard works?

**Comment by Helloyunho** [comment]
No, nothing works.

**Comment by Xiashangning** [comment]
...Of course you need to enable it and mark it as builtin

**Comment by Xiashangning** [comment]
And change Typecover's IOProbeScore to 9999

**Comment by Helloyunho** [comment]
After re mapping USB again, everything works!
