### ISSUE TITLE
SD Card Reader working, but showing as USB 3.0 - Possible fix?

### ISSUE THREAD

**Issue by billabongbruno** [Xiashangning/BigSurface#16]
Hey there again.
How is it going?

So, the SD card is fully working as the title indicated.
However, it shows up as a USB 3.0 device rather than Internal SD Card Reader (once you check under System Report).

It would be a nice touch to edit the BigSurface kext to address this purely "cosmetic" issue.

Someone has already come across this:
https://www.tonymacx86.com/threads/realtek-sd-card-reader.257141/page-2#post-2040364

Any thoughts?

**Comment by Xiashangning** [comment]
Our card reader is connected via USB not PCI

**Comment by therealjbenam** [comment]
> Hey there again. How is it going?
> 
> So, the SD card is fully working as the title indicated. However, it shows up as a USB 3.0 device rather than Internal SD Card Reader (once you check under System Report).
> 
> It would be a nice touch to edit the BigSurface kext to address this purely "cosmetic" issue.
> 
> Someone has already come across this: https://www.tonymacx86.com/threads/realtek-sd-card-reader.257141/page-2#post-2040364
> 
> Any thoughts?

Try looking at https://github.com/0xFireWolf/RealtekCardReaderFriend

It should do what you seek. I have already installed https://github.com/0xFireWolf/RealtekCardReader to great success and now finally my card reader on my SP6 is working.

I have tried RealtekCardReaderFriend but it stopped my OpenCore from booting. Probably was something I need to look at more in the config.

**Comment by Xiashangning** [comment]
@therealjbenam So without this kext your card reader does not work ?

**Comment by therealjbenam** [comment]
> @therealjbenam So without this kext your card reader does not work ?

Pretty sure it didn't work. Will try ASAP to disable the kext and I will try again.
