### ISSUE TITLE
可以用clover加载吗？

### ISSUE THREAD

**Issue by git2wing** [Xiashangning/BigSurface#17]
除了oc，可以用clover加载吗？
如果可以，如何配置config.plist？
也需要像oc一样加载多个plugin目录下的voodoo kext，再加载bigsurface.kext 吗？

**Comment by Xiashangning** [comment]
没试过…不过理论上你按我截图的顺序load应该没问题

**Comment by Xiashangning** [comment]
但是要加载我目录底下的那些plugin，而且要把原来的删掉
