### ISSUE TITLE
Can it be used in surface pro4

### ISSUE THREAD

**Issue by My-czr** [Xiashangning/BigSurface#18]
The Bigsurface kext Can it be used in surface pro4

**Comment by liuson945** [comment]
> The Bigsurface kext Can it be used in surface pro4

可以用，但是环境光感器无法使用！

**Comment by Xiashangning** [comment]
Show me your DSDT and IOReg, and please also tell me what functionality you would like to use it for, like ALS sensor ?

**Comment by My-czr** [comment]
> > The Bigsurface kext Can it be used in surface pro4
> 
> 可以用，但是环境光感器无法使用！

感谢，一会我尝试下。
