### ISSUE TITLE
Not an issue - Offering to help regarding cameras

### ISSUE THREAD

**Issue by billabongbruno** [Xiashangning/BigSurface#24]
Greetings once more.

It's been a while since we last traded thoughts.
How have you been?

I am here because I would like to help in the development of at least the cameras.

I have a SP4 (IPU3) and have several OS installed (Kali, Ubuntu, MacOS, Windows, ChromeOS).
I realized that it might be possible to drive the cameras, but you don't own any of those devices.

Seeing as you have already done so much, I would like to offer my help.

Is there anything I can do to help?

Best regards,
Bruno

**Comment by Xiashangning** [comment]
Check `linux-surface` repo, gather all related codes and understand the mecanism, then proceed to port the `libcamera` or at least port the initialization part of libcamera to macOS :)

**Comment by KoalafiedDev** [comment]
@billabongbruno Any update on this?
