### ISSUE TITLE
Surface Laptop 3: Not working

### ISSUE THREAD

**Issue by ajdarius** [Xiashangning/BigSurface#27]
Keyboard and Trackpad doesn't seem to be working with this kext.

**Comment by ajdarius** [comment]
I'm using OpenCore version 0.7.9, Hackintosh on macOS Catalina.

**Comment by misaka-20002** [comment]
Check if the kext is loaded correctly, as this kext is written for BigSur(and newer) originally.

**Comment by Xiashangning** [comment]
Discussion in #19
