### ISSUE TITLE
Battery indication

### ISSUE THREAD

**Issue by SmartBoy84** [Xiashangning/BigSurface#29]
Should battery indication work wjith this kext? I'm on the surface laptop and the battery indicator remains broken..

If not, a personal request - could you mod the [batterymanager](https://github.com/acidanthera/VirtualSMC/blob/master/Sensors/SMCBatteryManager/ACPIACAdapter.cpp) kext so that it always reports as being plugged in? This is because my setup of a surface laptop 1 being used as a desktop hackintosh is functioning almost perfectly apart from the fact that it won't operate in clamshell mode so when I close the lid it sleeps and my external display also consequently turns off. 

It seems all you'd need to change is ```bool connected = true``` and remove the function which follows? I'd do this myself and compile it however I really don't want to install the entire 30GB tool chain.

**Comment by Xiashangning** [comment]
Well, for the battery I can do my best to help you. Go to Windows and find out your UART device id then tell me

**Comment by SmartBoy84** [comment]
Would it be possible for you to make those simple changes and compile a kext for me? I currently don't have windows installed. 🥺

**Comment by Xiashangning** [comment]
macOS then, use `hackintool.app` and go to PCI tab, take a screenshot if you don't know which is UART, it is usually named UA00 or something like that.

**Comment by Xiashangning** [comment]
linux is even simpler, open terminal and type lspci, the output will do.

**Comment by SmartBoy84** [comment]
I really don't need a fully functioning battery indication as in my current setup the surface laptop is constantly plugged in. 

I just need it to report that it's plugged in so it can operate in clamshell mode. The changes I've detailed above should be sufficient. I would do it myself however I can't seem to compile it due to SDK problems; I might try some other time.

If you are unable to do this, feel free to close this issue I guess.

**Comment by SmartBoy84** [comment]
> Well, for the battery I can do my best to help you. Go to Windows and find out your UART device id then tell me

Well, I said I said a surface laptop 1 so ```9d27```?

**Comment by Xiashangning** [comment]
Hi, sorry for the delay, I am back from school work. If your device id is 9d27, then please try the new release. The battery should work properly, so as long as you plug in your charging cable, you can use it in clamshell mode. (Even if you don't need a fully functioning one...) :)

**Comment by SmartBoy84** [comment]
Thank you, I'll test this as soon as possible - I'll close this for now
