### ISSUE TITLE
Did this kext work On surface laptop2？

### ISSUE THREAD

**Issue by lizilong1993** [Xiashangning/BigSurface#32]
Hi， Xiashangning。
I had replace my voodoo kext ，but nothing changed， the keyboard and battery are still unworkable。Help！

**Comment by Xiashangning** [comment]
First of all, which surface do you have?

**Comment by Xiashangning** [comment]
Ok, it’s my bad to ignore your title
i need output of sudo dmesg | grep -E ‘SurfaceSerial|UART’
