### ISSUE TITLE
Keyboard for the surface laptop 1?

### ISSUE THREAD

**Issue by SmartBoy84** [Xiashangning/BigSurface#34]
Hey, I was just wondering if you have any plans on supporting the surface laptop 1 `9d27`? The last time I tested this, absolutely nothing changed (keyboard didn't work and battery readout wasn't functional).

As you said in my other issue, battery readout has been resolved so I'll test this - does keyboard input work as well?

**Comment by Xiashangning** [comment]
No keyboard is not supported yet
Does your battery works now with new release?

**Comment by SmartBoy84** [comment]
No, it doesn't - if it's any indication of what's going wrong the trackpad doesn't work either. It works (along with the complete set of gestures) with VoodooI2C. Does that mean the kext fails to load?

When do you plan on supporting the keyboard? If you need help, I'd suggest contacting Qzed as he's the prime developer of  surface drivers on linux [here](https://github.com/linux-surface/linux-surface)

**Comment by Xiashangning** [comment]
If it doesn't work, I need logs.
Attach the output of `sudo dmesg | grep -E "VoodooUART|SurfaceSerial|SurfaceBattery"`

**Comment by Xiashangning** [comment]
Closed as unresponsive.
