### ISSUE TITLE
Version 6.0 not run in Surface Book 3

### ISSUE THREAD

**Issue by rsknewt** [Xiashangning/BigSurface#36]
i tried version 6.0 but touchpad and keyboard not working at all

**Comment by Xiashangning** [comment]
Hi, can you first try version 5.0? Does that release work?
And for version 6.0, please attach your ioreg and output of sudo dmesg | grep -E "SurfaceSerial|SurfaceLaptop|SurfaceManagement|IntelPrecise"

**Comment by rsknewt** [comment]
Use version 5.0 can all work except touchscreen not working

**Comment by Xiashangning** [comment]
So I need your ioreg and terminal output of `sudo dmesg | grep -E "SurfaceSerial|SurfaceLaptop|SurfaceManagement|IntelPrecise"`

(PS: remember to add `DebugEnhancer.kext` to your config)

**Comment by Xiashangning** [comment]
@rsknewt Hi, you are not responding, so I assume that it works now on SB3.
