### ISSUE TITLE
Trackpad stops working after long time closing lid

### ISSUE THREAD

**Issue by stedio** [Xiashangning/BigSurface#37]
Just noticed the trackpad stops working if the lid is closed for a longer time (10-20 mins), for shorter time, seems no such issue. Unplug and plug doesn't help, the keyboard works fine. 

Running 10.14 with recompiled Big Surface 

I guess it related to the power management? Any suggestions? Thank you

**Comment by Xiashangning** [comment]
I haven't experienced your issue on my SP7 in big sur or monterey. The Type Cover is connected via USB, thus power managed by USB driver. If there is something wrong, that is your config's or USB driver's issue, not `BigSurface`, as it doesn't manage the power for Type Cover

**Comment by stedio** [comment]
But it's weird that the keyboard works totally fine, I guess the keyboard and the touchpad are sharing the same USB port, as I can only see one 'Surface TypeCover' in the USB tree?
