### ISSUE TITLE
Surface Pro 6 latest kext don't works

### ISSUE THREAD

**Issue by cs59** [Xiashangning/BigSurface#39]
I have surface pro 6 with macos monterey latest installed on it. before i was using your old kext which u made for someone issue before if i remembered and tried the kext and it working fine but afcourse no trackpad found in settings but trackpad and all gestures work and also hardware power volume keys, other fearures like battery afcourse not work, and I tried your ssdt and that latest bigsurface kext and when i booted with your latest kext then it not booting, If you have time to make this kext fully or mostly support sp6 then am ready for all information u want also I can install linux and send what u want for this kext to make work for sp6, hope u reply I will wait
![photo_2022-07-03_06-15-19](https://user-images.githubusercontent.com/68501788/177027455-e5140ebf-2dd4-492e-b150-e3e26ea3350d.jpg)
g

**Comment by cs59** [comment]
Current bigsurface kext am using is this -
[BigSurfaceSP6.kext.zip](https://github.com/Xiashangning/BigSurface/files/9034163/BigSurfaceSP6.kext.zip)

**Comment by Xiashangning** [comment]
I need ioreg, disable BIgSurface and send me the ioreg

**Comment by cs59** [comment]
> I need ioreg, disable BIgSurface and send me the ioreg

okay, should i remove the bigsurface fully then send ioreg?

**Comment by Xiashangning** [comment]
just not enable it in config.plist

**Comment by cs59** [comment]
> just not enable it in config.plist

okay

**Comment by cs59** [comment]
> just not enable it in config.plist
Opened ioreg which information should i send u?
![12D87BE9-9B8B-43A9-866A-32E1BDF630B1](https://user-images.githubusercontent.com/68501788/177028266-0c433a90-cc40-4ec3-9e20-b39aea046730.jpeg)

**Comment by Xiashangning** [comment]
save this

**Comment by cs59** [comment]
> save this

Ok sending

**Comment by Xiashangning** [comment]
???
You HAVE TO SAVE THIS TO A FILE AND SEND THAT FILE, in `File`->`Save`
you attached NOTHING

**Comment by cs59** [comment]
> ???
> You HAVE TO SAVE THIS TO A FILE AND SEND THAT FILE, in `File`->`Save`
> you attached NOTHING
`

> ???
> You HAVE TO SAVE THIS TO A FILE AND SEND THAT FILE, in `File`->`Save`
> you attached NOTHING

Here’s link: can’t attach files from device i think so here link https://drive.google.com/file/d/1AUv9wy4scFcC90Uf4tsdzh6txAWTqOmQ/view?usp=drivesdk

**Comment by Xiashangning** [comment]
Why? compress it to a zip file and drag it here
I cannot open this link

**Comment by cs59** [comment]
> Why? compress it to a zip file and drag it here
> I cannot open this link

Ok wait

**Comment by cs59** [comment]
> Why? compress it to a zip file and drag it here
> I cannot open this link
here file Korey
[LJSS’s MacBook Pro.zip](https://github.com/Xiashangning/BigSurface/files/9034228/LJSS.s.MacBook.Pro.zip)

**Comment by Xiashangning** [comment]
Try this one, remember to reenable BigSurface 
[BigSurface.kext.zip](https://github.com/Xiashangning/BigSurface/files/9034240/BigSurface.kext.zip)

**Comment by cs59** [comment]
> Try this one, remember to reenable BigSurface
> [BigSurface.kext.zip](https://github.com/Xiashangning/BigSurface/files/9034240/BigSurface.kext.zip)

Ok, just replace the kext with this one in kext folder and enable it, ryt?

**Comment by cs59** [comment]
> Try this one, remember to reenable BigSurface
> [BigSurface.kext.zip](https://github.com/Xiashangning/BigSurface/files/9034240/BigSurface.kext.zip)

Stuck here
![Uploading 6D1B93A8-77CB-4ECF-997A-015932E1E9AD.jpeg…]()

**Comment by cs59** [comment]
> Try this one, remember to reenable BigSurface
> [BigSurface.kext.zip](https://github.com/Xiashangning/BigSurface/files/9034240/BigSurface.kext.zip)

Stuck here
![Uploading 1FFAAE6B-7DD8-4EC0-84E1-474C952BC2C9.jpeg…]()

**Comment by cs59** [comment]
> Try this one, remember to reenable BigSurface [BigSurface.kext.zip](https://github.com/Xiashangning/BigSurface/files/9034240/BigSurface.kext.zip)

Stuck here
![photo_2022-07-03_07-24-52](https://user-images.githubusercontent.com/68501788/177029699-324859e7-a646-46df-9e60-6e2dbcb784fa.jpg)
e

**Comment by Xiashangning** [comment]
[BigSurface.kext.zip](https://github.com/Xiashangning/BigSurface/files/9034256/BigSurface.kext.zip)

**Comment by cs59** [comment]
> [BigSurface.kext.zip](https://github.com/Xiashangning/BigSurface/files/9034256/BigSurface.kext.zip)

Different error last output every boot
![photo_2022-07-03_13-05-42](https://user-images.githubusercontent.com/68501788/177030029-5c427aac-f410-44cc-b995-14c27942f76b.jpg)
![photo_2022-07-03_13-05-45](https://user-images.githubusercontent.com/68501788/177030031-d06a96c4-b2dc-407a-ba9d-413cbac8df8d.jpg)
t

**Comment by cs59** [comment]
> > [BigSurface.kext.zip](https://github.com/Xiashangning/BigSurface/files/9034256/BigSurface.kext.zip)
> 
> Different error last output every boot ![photo_2022-07-03_13-05-42](https://user-images.githubusercontent.com/68501788/177030029-5c427aac-f410-44cc-b995-14c27942f76b.jpg) ![photo_2022-07-03_13-05-45](https://user-images.githubusercontent.com/68501788/177030031-d06a96c4-b2dc-407a-ba9d-413cbac8df8d.jpg) t

btw it gone past before 1 error 'previous shutdown error'

**Comment by Xiashangning** [comment]
[BigSurface.kext.zip](https://github.com/Xiashangning/BigSurface/files/9034271/BigSurface.kext.zip)

**Comment by cs59** [comment]
> [BigSurface.kext.zip](https://github.com/Xiashangning/BigSurface/files/9034271/BigSurface.kext.zip)

this one working bro, trackpad and gestures work but as usual setting don't find trackpad, power volume button working. can we make more compatibility for sp6
![photo_2022-07-03_13-21-25](https://user-images.githubusercontent.com/68501788/177030547-d8454473-a8d3-4e71-b189-f8501905b301.jpg)

**Comment by Xiashangning** [comment]
[BigSurface.kext.zip](https://github.com/Xiashangning/BigSurface/files/9034289/BigSurface.kext.zip)
If this one works, then go download `IPTSDaemon` from my other repo, install it as instructed and test if touch screen works

**Comment by cs59** [comment]
> [BigSurface.kext.zip](https://github.com/Xiashangning/BigSurface/files/9034289/BigSurface.kext.zip)
> If this one works, then go download `IPTSDaemon` from my other repo, install it as instructed and test if touch screen works

Okay

**Comment by cs59** [comment]
> [BigSurface.kext.zip](https://github.com/Xiashangning/BigSurface/files/9034289/BigSurface.kext.zip)
> If this one works, then go download `IPTSDaemon` from my other repo, install it as instructed and test if touch screen works

Can’t install bro getting errors
![B103AE7C-8097-433E-BA8B-9D4391C339B8](https://user-images.githubusercontent.com/68501788/177031907-1b9b502b-8ef8-4610-9964-15ff7b6fa5ef.jpeg)

**Comment by cs59** [comment]
> [BigSurface.kext.zip](https://github.com/Xiashangning/BigSurface/files/9034289/BigSurface.kext.zip)
> If this one works, then go download `IPTSDaemon` from my other repo, install it as instructed and test if touch screen works

Seems like it’s not copying the file dunno why, let me try disabling the sip, else will copy the files manually and see
![23B6EA32-1FD7-48B2-B9F3-25343CFDC382](https://user-images.githubusercontent.com/68501788/177032026-d3bb4dff-73f0-4686-a505-9a174b80f389.jpeg)

**Comment by cs59** [comment]
> > [BigSurface.kext.zip](https://github.com/Xiashangning/BigSurface/files/9034289/BigSurface.kext.zip)
> > If this one works, then go download `IPTSDaemon` from my other repo, install it as instructed and test if touch screen works
> 
> Seems like it’s not copying the file dunno why, let me try disabling the sip, else will copy the files manually and see ![23B6EA32-1FD7-48B2-B9F3-25343CFDC382](https://user-images.githubusercontent.com/68501788/177032026-d3bb4dff-73f0-4686-a505-9a174b80f389.jpeg)

Okay solved the error, just have to -R
![BAEBC828-78B9-409B-91F5-21E1D7DD1D49](https://user-images.githubusercontent.com/68501788/177032329-7a041488-37d4-4084-89f6-f6ec7c0d89a0.jpeg)

**Comment by Xiashangning** [comment]
I don't understand what you are doing.
Really, a kind reminder: do you install `BigSurface.kext` like this?

**Comment by cs59** [comment]
> I don't understand what you are doing.
> Really, a kind reminder: do you install `BigSurface.kext` like this?

No bro, bigsurface i replaced in windows from diskgenius and working perfectly fine, and for IPTSDaemon, when i run install sh file then it shows many errors, so what i done is that i opened sh file and manually copy all commands one by one and accoring to their location i cd in terminal and then pasted commands one by one and installed like that

**Comment by cs59** [comment]
> I don't understand what you are doing.
> Really, a kind reminder: do you install `BigSurface.kext` like this?

Also see this, i install the daemon successfully, also it doesn’t execute the last command if not run with sudo, if i run with sudo then it works see
![60BA48A4-574D-4221-A24A-37CEFD1FF38E](https://user-images.githubusercontent.com/68501788/177033287-9f13e850-c58a-48f0-a50b-3853e6ffc80b.jpeg)

**Comment by Xiashangning** [comment]
> Okay solved the error, just have to -R

Also, that is not SOLVED, that is WORSE
Why would you install anything from the project folder ???????
Here is what you will do:
You go to the `release section` of IPTSDaemon repo main page
You download the pre-release zip file
You unzip the file you downloaded
You open Terminal
You cd to that folder
You run the install script

**Comment by cs59** [comment]
> > Okay solved the error, just have to -R
> 
> Also, that is not SOLVED, that is WORSE Why would you install anything from the project folder ??????? Here is what you will do: You go to the `release section` of IPTSDaemon repo main page You download the pre-release zip file You unzip the file you downloaded You open Terminal You cd to that folder You run the install script

Extremely sorry bro, i tried to see release but I thought we have to so it manually, release name really too small btw sorry 
![E4DF64D6-DC39-4381-84BD-5B1BBB8A96D3](https://user-images.githubusercontent.com/68501788/177033396-48559864-e6ca-4599-b729-db17b8c7c0c7.jpeg)

**Comment by cs59** [comment]
> > > Okay solved the error, just have to -R
> > 
> > 
> > Also, that is not SOLVED, that is WORSE Why would you install anything from the project folder ??????? Here is what you will do: You go to the `release section` of IPTSDaemon repo main page You download the pre-release zip file You unzip the file you downloaded You open Terminal You cd to that folder You run the install script
> 
> Extremely sorry bro, i tried to see release but I thought we have to so it manually, release name really too small btw sorry ![E4DF64D6-DC39-4381-84BD-5B1BBB8A96D3](https://user-images.githubusercontent.com/68501788/177033396-48559864-e6ca-4599-b729-db17b8c7c0c7.jpeg)

Okay all good now, I will follow next 
![Uploading 4F10796A-880F-4A56-A42D-2E23A81267BC.jpeg…]()

**Comment by cs59** [comment]
> > Okay solved the error, just have to -R
> 
> Also, that is not SOLVED, that is WORSE Why would you install anything from the project folder ??????? Here is what you will do: You go to the `release section` of IPTSDaemon repo main page You download the pre-release zip file You unzip the file you downloaded You open Terminal You cd to that folder You run the install script

All good now, will follow next things
![6A4C7DE0-B50F-441D-802D-DE921D7057D0](https://user-images.githubusercontent.com/68501788/177033632-2986fb47-cc18-4c41-8ca9-f491c718850c.jpeg)

**Comment by Xiashangning** [comment]
No, not good. You do not need `sudo`, rerun the script

**Comment by Xiashangning** [comment]
If everything works as expected, your touch screen should work

**Comment by cs59** [comment]
> If everything works as expected, your touch screen should work

Okay, rerun the script and no errors at all, but touchscreen not working as expected lol 
![53D8B130-AB3F-4F69-9218-239A0582648D](https://user-images.githubusercontent.com/68501788/177034080-fcf03dfa-3abc-445c-b825-1b27b4c36616.jpeg)

**Comment by cs59** [comment]
> > If everything works as expected, your touch screen should work
> 
> Okay, rerun the script and no errors at all, but touchscreen not working as expected lol ![53D8B130-AB3F-4F69-9218-239A0582648D](https://user-images.githubusercontent.com/68501788/177034080-fcf03dfa-3abc-445c-b825-1b27b4c36616.jpeg)

Also bro, I tried to check if the daemon starts after restarting my laptop automatically but the daemon not started as i checked it by running last command of sh script after restrating, it only enabled daemon when we run that command

**Comment by cs59** [comment]
> > > If everything works as expected, your touch screen should work
> > 
> > 
> > Okay, rerun the script and no errors at all, but touchscreen not working as expected lol ![53D8B130-AB3F-4F69-9218-239A0582648D](https://user-images.githubusercontent.com/68501788/177034080-fcf03dfa-3abc-445c-b825-1b27b4c36616.jpeg)
> 
> Also bro, I tried to check if the daemon starts after restarting my laptop automatically but the daemon not started as i checked it by running last command of sh script after restrating, it only enabled daemon when we run that command

![56C269C0-F0BE-453A-A22A-49E1D97FBD7F](https://user-images.githubusercontent.com/68501788/177034190-52dd1553-3a71-4e0c-a078-6f135fc1d85e.jpeg)

**Comment by Xiashangning** [comment]
run `IPTSDaemon` manually and see what is the error

**Comment by cs59** [comment]
> run `IPTSDaemon` manually and see what is the error

Here,
![4FB57934-A700-430D-9351-B1B6D8495348](https://user-images.githubusercontent.com/68501788/177034237-f058dca1-103c-4dce-8af4-cc1feaa94d7e.jpeg)

**Comment by Xiashangning** [comment]
`sudo dmesg | grep -E "SurfaceMana|IntelPrecise"`

**Comment by cs59** [comment]
> sudo dmesg | grep -E "SurfaceMana|IntelPrecise"

Runned no error comes, now?

**Comment by cs59** [comment]
> sudo dmesg | grep -E "SurfaceMana|IntelPrecise"

Same, Could not find IntelPreciseTouchusDriver when trying to run IPTSDaemon

**Comment by Xiashangning** [comment]
Then you should add `DebugEnhancer.kext` and reboot.
I need output of this

**Comment by cs59** [comment]
> Then you should add `DebugEnhancer.kext` and reboot.
> I need output of this

Okay, will get this kext and will reboot, and will message you

**Comment by cs59** [comment]
> Then you should add `DebugEnhancer.kext` and reboot.
> I need output of this

Ok, added debugenchancer kext and now booted, now what to do next to get output?

**Comment by Xiashangning** [comment]
Open Terminal and send me output of `sudo dmesg | grep -E "SurfaceMana|IntelPrecise"`

**Comment by cs59** [comment]
> Open Terminal and send me output of `sudo dmesg | grep -E "SurfaceMana|IntelPrecise"`

Sadly it’s not showing any output, you see can here, debug kext also enabled
![D6BF6310-1AF7-49B6-BAA4-09F0C51EF9B6](https://user-images.githubusercontent.com/68501788/177035136-ee988e61-b775-4549-b90b-5aeb6aa546f0.jpeg)
![144156ED-FDBF-4829-BE7A-308FE9AC1599](https://user-images.githubusercontent.com/68501788/177035140-c9dbdb2c-3c16-4aff-b4c2-f39d184ac661.jpeg)

**Comment by cs59** [comment]
> sudo dmesg | grep -E "SurfaceMana|IntelPrecise"

I seen on DebugEnchancer website that workaround is going on macos 12 and above, that why it maybe not showing any output

**Comment by Xiashangning** [comment]
Try this one and send me `sudo dmesg | grep -E "SurfaceMana|IntelPrecise"`
[BigSurface.kext.zip](https://github.com/Xiashangning/BigSurface/files/9037894/BigSurface.kext.zip)

**Comment by cs59** [comment]
> Try this one and send me `sudo dmesg | grep -E "SurfaceMana|IntelPrecise"`
> [BigSurface.kext.zip](https://github.com/Xiashangning/BigSurface/files/9037894/BigSurface.kex
<img width="1368" alt="Screenshot 2022-07-04 at 2 38 50 AM" src="https://user-images.githubusercontent.com/68501788/177128060-bb4c781f-deb1-45fd-8188-beb7e979c4ea.png">


okay finally got output

**Comment by cs59** [comment]
> > Try this one and send me `sudo dmesg | grep -E "SurfaceMana|IntelPrecise"`
> > [BigSurface.kext.zip](https://github.com/Xiashangning/BigSurface/files/9037894/BigSurface.kex
> 
> <img alt="Screenshot 2022-07-04 at 2 38 50 AM" width="1368" src="https://user-images.githubusercontent.com/68501788/177128060-bb4c781f-deb1-45fd-8188-beb7e979c4ea.png">
> 
> okay finally got output

what the heeeeeckkkkkk, touchscreen perfectly man lol am crying bro thnx so much lol never expected specially touchscreen seriously u r very genius bro u makes impossible to possible, I hope we can now fix more things and increase compatibility for SP6 :)

**Comment by Xiashangning** [comment]
Try this one
[BigSurface.kext.zip](https://github.com/Xiashangning/BigSurface/files/9038339/BigSurface.kext.zip)

**Comment by cs59** [comment]
> Try this one
> [BigSurface.kext.zip](https://github.com/Xiashangning/BigSurface/files/9038339/BigSurface.kext.zip)

Stuck here
![50DB27D9-1845-40D5-85BE-AF62E03AEEDB](https://user-images.githubusercontent.com/68501788/177131752-8851a5d7-8ee9-4f5a-9311-9beee16aefe9.jpeg)
![C104E85C-CF8C-46E4-A8F7-C4207505A2F3](https://user-images.githubusercontent.com/68501788/177131791-ac7fa359-26e1-40b5-ad47-7bf8b2e89070.jpeg)

**Comment by Xiashangning** [comment]
I need your dsdt

**Comment by cs59** [comment]
> I need your dsdt

sorry for being late, here is my dsdt
[DSDT-SP-6.zip](https://github.com/Xiashangning/BigSurface/files/9039305/DSDT-SP-6.zip)

**Comment by Xiashangning** [comment]
[BigSurface.kext.zip](https://github.com/Xiashangning/BigSurface/files/9039388/BigSurface.kext.zip)

**Comment by cs59** [comment]
> [BigSurface.kext.zip](https://github.com/Xiashangning/BigSurface/files/9039388/BigSurface.kext.zip)

worked but any changes?
Also am getting random clicks after my touchscreen was started working

https://user-images.githubusercontent.com/68501788/177156672-c8a7701d-fed0-452b-9899-bf94471fbf5d.MOV

**Comment by Xiashangning** [comment]
i need logs
sudo dmesg | grep SurfaceSerial

**Comment by cs59** [comment]
> i need logs
> sudo dmesg | grep SurfaceSerial

![7EAA3859-5448-4AF3-93F3-F5BF17FAE22A](https://user-images.githubusercontent.com/68501788/177163398-a2a450ca-95de-42a4-98d1-21e96324a6aa.jpeg)

**Comment by cs59** [comment]
> i need logs
> sudo dmesg | grep SurfaceSerial

Update: the random clicking problem was seems solved now :),
Now possible to get this last thing ‘battery’?

**Comment by cs59** [comment]
> > i need logs
> > sudo dmesg | grep SurfaceSerial
> 
> Update: the random clicking problem was seems solved now :), Now possible to get this last thing ‘battery’?

Okay it’s not fixed, even it’s getting worst now, any command to disable it and if fix also available?

**Comment by Xiashangning** [comment]
If not stuck at booting, I need the same log
[BigSurface.kext.zip](https://github.com/Xiashangning/BigSurface/files/9052194/BigSurface.kext.zip)

**Comment by cs59** [comment]
> If not stuck at booting, I need the same log
> [BigSurface.kext.zip](https://github.com/Xiashangning/BigSurface/files/9052194/BigSurface.kext.zip)

Stuck 
![1A1EDA1F-6A17-42AD-8249-63F85ADF1A03](https://user-images.githubusercontent.com/68501788/177499282-d3bfe75a-3055-4b13-82ad-d396535a6994.jpeg)

**Comment by Xiashangning** [comment]
[BigSurface.kext.zip](https://github.com/Xiashangning/BigSurface/files/9054622/BigSurface.kext.zip)

**Comment by cs59** [comment]
> BigSurface.kext.zip

![F8EE0BBE-854D-4C07-A659-D371295F4949](https://user-images.githubusercontent.com/68501788/177568810-fe25f80f-7871-4d2c-973c-35eb0bf0024f.jpeg)

**Comment by Xiashangning** [comment]
So at this point, I can safely say that unfortunately your problem is not related to `BigSurface`, as referred in this issue #35 , BigSurface is proved to be working properly for battery on SP6 even in 10.14. You MUST have something misconfigured in Opencore's config or ACPI or else. The driver itself is compatible

**Comment by Xiashangning** [comment]
My guess is very likely on ACPI side

**Comment by cs59** [comment]
> My guess is very likely on ACPI side

so do u wanna check out my EFI then? or we can't do anything for this?

**Comment by cs59** [comment]
> My guess is very likely on ACPI side

Hey, i tried the kext which u given in which touchscreen was working and i ran this command and got this output
![DAE1536E-9FBC-4373-88FB-0C7AA10BC2C7](https://user-images.githubusercontent.com/68501788/177599365-ef271f81-f665-4f36-8735-8db4eba95c56.jpeg)

**Comment by Xiashangning** [comment]
> > My guess is very likely on ACPI side
> 
> so do u wanna check out my EFI then? or we can't do anything for this?

I do not have a SP6 so I cannot help you check your own EFI, I would suggest that you ask other SP6 owners about their EFI and compare it to yours.

**Comment by cs59** [comment]
> > > My guess is very likely on ACPI side
> > 
> > 
> > so do u wanna check out my EFI then? or we can't do anything for this?
> 
> I do not have a SP6 so I cannot help you check your own EFI, I would suggest that you ask other SP6 owners about their EFI and compare it to yours.

Okay, I seen the issue u mentioned and read carefully and after that I got the idea to try smcbattery manager kexts, so get the zip, extract and copied all smc’s kexts in my EFI and taken snapshot after that I rebooted then it started showing battery and it’s preferences also but it always showing 100% battery, i tried to also use dsdt from the issue u given link but still it always keep 100% battery, it do sometimes detect that am plugged in but after that always show on battery and 100%, any idea and help will be appreciated if u can

**Comment by cs59** [comment]
> > > My guess is very likely on ACPI side
> > 
> > 
> > so do u wanna check out my EFI then? or we can't do anything for this?
> 
> I do not have a SP6 so I cannot help you check your own EFI, I would suggest that you ask other SP6 owners about their EFI and compare it to yours.

Okay, I seen the issue u mentioned and read carefully and after that I got the idea to try smcbattery manager kexts, so get the zip, extract and copied all smc’s kexts in my EFI and taken snapshot after that I rebooted then it started showing battery and it’s preferences also but it always showing 100% battery, i tried to also use dsdt from the issue u given link but still it always keep 100% battery, it do sometimes detect that am plugged in but after that always show on battery and 100%, any idea and help will be appreciated if u can
![1DD06852-42E0-4EEB-8086-D1A450677C92](https://user-images.githubusercontent.com/68501788/177752695-35609491-dc43-4de9-91e1-4517d355fc52.jpeg)

**Comment by sergeykoznov** [comment]
@cs59 did you fix the battery status?

**Comment by cs59** [comment]
> @cs59 did you fix the battery status?
> 
> 

Sadly not, tried to much but no success at all

**Comment by Xiashangning** [comment]
See the updated README (`how to install` section) and check you EFI config

**Comment by cs59** [comment]
> See the updated README (`how to install` section) and check you EFI config

okay
