### ISSUE TITLE
Compiled .kext in releases

### ISSUE THREAD

**Issue by MrHomebrew** [Xiashangning/BigSurface#4]
Would it be possible to get a compiled .kext in the release section?

**Comment by Xiashangning** [comment]
Got it, I will update my repo and release a beta version of it, (surface typecover keyboard & touchpad full support, power and volume buttons maybe)

**Comment by plsh2me** [comment]
@Xiashangning I will wait to give a try on my surface pro 7. Thank you for your efforts.

**Comment by MrHomebrew** [comment]
Sounds great 👍

**Comment by Xiashangning** [comment]
@plsh2me @MrHomebrew Done, please try it and let me know if it works properly.

**Comment by plsh2me** [comment]
@Xiashangning I am pleased to confirm you that the kext works as expected with your recommended config settings on my Surface pro 7 (with Surface pro type cover -model 1725). 
Hope you will proceed to add more functions in future version.
Thank you very much.

**Comment by jackjack1-su** [comment]
Emmm...
I suggest to close this issue because the kext is released.
