### ISSUE TITLE
Nothing works on surface pro 5

### ISSUE THREAD

**Issue by kevin-Curry** [Xiashangning/BigSurface#41]
I’ve tested everything. But it seems nothing works on my laptop. Including battery and trackpad. Starred and waiting for touchscreen for surface pro 5!

**Comment by Xiashangning** [comment]
Trackpad should be working, as for battery and touchscreen, I need your device id for UART and IntelManagementEngine. You can either send me your screenshot of `hackintool`'s PCIe tab or find them in device manager in Windows.
Also ioreg will be very helpful

**Comment by kevin-Curry** [comment]
OK I'll try.

PS
when will you release the touch screen support on SP6. cause I saw you just updated but no new release

**Comment by kevin-Curry** [comment]
![图像2022-7-19 上午10 59_副本](https://user-images.githubusercontent.com/62877110/179655542-15e6ab15-ffd6-4cce-ba15-cb03fb9928f1.jpg)
Here's the screenshot. And trackpad does work. Looking for the touchscreen and battery.

**Comment by Xiashangning** [comment]
I need ioreg, try the pre-release kext first, battery and touchscreen should work

**Comment by kevin-Curry** [comment]
only v5 works

**Comment by kevin-Curry** [comment]
v6 and pre-release doesn't work

**Comment by Xiashangning** [comment]
What is not working? Attach output of `sudo dmesg | grep -E "SurfaceSerial|VoodooUART|SurfaceBattery|SurfaceMana"`

**Comment by kevin-Curry** [comment]
And ioreg/Users/kevinzhou/Library/Messages/Attachments/ea/10/B1A5E6BE-8B79-4E3F-99B8-3C6A6213B8FF/图像2022-7-19 上午10.59.heic

**Comment by kevin-Curry** [comment]
Nothing is working and no output after I type that.

**Comment by Xiashangning** [comment]
you need debugenhancer.kext

**Comment by kevin-Curry** [comment]
where can I download

**Comment by kevin-Curry** [comment]
hmmm.
None of your release can drive the trackpad.
I downloaded a version that edited by other one.
I don't know which version actually did he use.
My OpenCore version is 0.8.1 and macOS Monterey.
I don't know if it made something wrong.

**Comment by kevin-Curry** [comment]
Sorry.
Version 3.0 does work.
But 1/2/4/5/6/6.1 doesn't work.

**Comment by Xiashangning** [comment]
I need you to install DebugEnhancer.kext (just search it on github) and attach the output and the ioreg saved from ioregistryexplorer.app
It is meaningless to try different version. That is a waste of time

**Comment by kevin-Curry** [comment]
![图像2022-7-19 下午3 01_副本](https://user-images.githubusercontent.com/62877110/179687438-06d9740a-7ff5-4303-8504-ca7d75e3aa1a.jpg)
![图像2022-7-19 下午3 03_副本](https://user-images.githubusercontent.com/62877110/179687453-d3d170ed-be77-497d-98ff-bd470676e17a.jpg)
Is these what you want?

**Comment by Xiashangning** [comment]
Have you updated your Lilu and VirtualSMC to the latest version?

**Comment by kevin-Curry** [comment]
nope, I'll try

**Comment by kevin-Curry** [comment]
ok I updated them.
Nothing changes

**Comment by Xiashangning** [comment]
What about the output? `sudo dmesg | grep -E "SurfaceSerial|VoodooUART|SurfaceBattery|SurfaceMana" -A 5 -B 5`

**Comment by kevin-Curry** [comment]
![图像2022-7-19 下午9 25_副本](https://user-images.githubusercontent.com/62877110/179761771-980f4dd6-071a-4954-877c-d4b4ce77ff67.jpg)

**Comment by Xiashangning** [comment]
Try this one
[BigSurface.kext.zip](https://github.com/Xiashangning/BigSurface/files/9141941/BigSurface.kext.zip)

**Comment by kevin-Curry** [comment]
Still not working.

**Comment by Xiashangning** [comment]
I NEED THE OUTPUT, PLZ
How would you expect me to help you debug without telling me what is wrong?

**Comment by kevin-Curry** [comment]
![图像2022-7-20 上午10 34_副本](https://user-images.githubusercontent.com/62877110/179883756-db95de71-c72d-4a74-ae0a-470f20d0f1c0.jpg)

**Comment by Xiashangning** [comment]
sudo dmesg | grep -E "SurfaceSSurfaceB|SurfaceM" -A 10

**Comment by kevin-Curry** [comment]
<img width="898" alt="截屏2022-07-20 上午10 44 13" src="https://user-images.githubusercontent.com/62877110/179884790-9ed73975-befb-46b3-8316-ebc0b399cf11.png">

**Comment by Xiashangning** [comment]
sudo dmesg | grep -E "SurfaceS|SurfaceB|SurfaceM" -B 10
sorry

**Comment by kevin-Curry** [comment]
<img width="1177" alt="截屏2022-07-20 上午10 55 43" src="https://user-images.githubusercontent.com/62877110/179886219-20981b9e-6c24-47dd-93d5-1757c54dcdbb.png">

**Comment by Xiashangning** [comment]
you should remove smcbatterymanager

**Comment by kevin-Curry** [comment]
Yeah, GREAT.
Trackpad and Battery works.
But touchscreen still not working.

**Comment by kevin-Curry** [comment]
What command shall I type this time?

**Comment by Xiashangning** [comment]
you should install IPTSDaemon, see my other repo

**Comment by kevin-Curry** [comment]
OK.
 IT WORKS!!!
 AWESOME!
