### ISSUE TITLE
Surface Laptop 3 13.5

### ISSUE THREAD

**Issue by AndreyFadeevKharkov** [Xiashangning/BigSurface#42]
Good afternoon, unfortunately the touchscreen of my Surface Laptop 3 13.5 does not work. I'd appreciate it if you could fix it, thanks.

**Comment by Xiashangning** [comment]
I need output of `sudo dmesg | grep -E "SurfaceMana|IntelPrecise"` (with DebugEnhancer enabled)

**Comment by Xiashangning** [comment]
Closed as unresponsive
