### ISSUE TITLE
Surface Book 3 over heating

### ISSUE THREAD

**Issue by MetalChris87** [Xiashangning/BigSurface#44]
Hi,

I had everything working on Monterey except for bluetooth as the BigSurface kext won't work when bluetooth kext is also installed, no idea, but I am fine not having Bluetooth.

My issue is the screen part of my Surface Book 3 where the CPU etc all sits is over heating. It doesn't happen every time, I can be using for hours with no issues everything great including touch screen, and then it will over heat for no reason. Or I can boot up after not being turned on for hours and it will be over heat immediately. And sometimes when it's asleep I will touch the lid and I can feel it extremely hot get worried and turn it off for a few hours.  I use my laptop for work and so I had to revert back to windows for now.  I think the Surface Book has temperature driver which installs with windows which may not have a Mac equivalent.

Any ideas? I was thinking maybe performance mode is set too high? not sure.

BTW I also get this same over heating issue with BigSur.

Thanks

**Comment by kevin-Curry** [comment]
Wait.
You meant book 3 can touch right

**Comment by MetalChris87** [comment]
Surface Book 3 has working touch screen. Yes.

**Comment by Xiashangning** [comment]
BigSurface has nothing to do with buletooth at all
As for your overheating problem, plz first make sure that it is CAUSED by BigSurface. For example, if you disable BigSurface, will the overheating be gone?

**Comment by MetalChris87** [comment]
I know, I was just trying to convey that everything is working great except for bluetooth as for some reason it clashes with the BigSurface Kext. I can only have one active, but that doesn't bother me. 
I will boot up MacOs Monterey tonight and test without BigSurface to see how it reacts. 

Thanks

**Comment by MetalChris87** [comment]
I disabled BigSurface and the overheating issue remained. I edited the Plist for BigSurface to change the performance mode from 1 to 0 and immediately after reboot the fans turned on rapidly and it is staying cool now. I will try different values to see which works best for me as I feel it has slowed down my laptop a little bit. 

Edit** I have tried performance mode 2,3 & 4 as well. 4 is working the best without over heating. 

Thanks

**Comment by Xiashangning** [comment]
Interesting, so actually the `best performance` mode works best

**Comment by kevin-Curry** [comment]
> Surface Book 3 has working touch screen. Yes.

Would you please send me a link of you EFI folder plz.

**Comment by MetalChris87** [comment]
My Efi for Monterey is here 
https://drive.google.com/file/d/1pmqYzsL6TwmGODvsHqhrRWfjYjxlRSEy/view?usp=sharing

But I think the Efi in here is version 5. Download version 6 and follow the steps on this GitHub for touchscreen functionality.

**Comment by kevin-Curry** [comment]
> My Efi for Monterey is here https://drive.google.com/file/d/1pmqYzsL6TwmGODvsHqhrRWfjYjxlRSEy/view?usp=sharing
> 
> But I think the Efi in here is version 5. Download version 6 and follow the steps on this GitHub for touchscreen functionality.

wait, 15''or13.5''

**Comment by MetalChris87** [comment]
My laptop is 15inch.
