### ISSUE TITLE
Feature Request: Surface Pro 4 触摸屏支持

### ISSUE THREAD

**Issue by ilharp** [Xiashangning/BigSurface#45]
才看到本项目已经支持触摸屏了  特地前来膜拜  大佬太强了

个人现在正式环境下使用的是本项目的 `v4` 版本，想升级获得触摸屏支持  但触摸屏目前貌似还没有 Surface Pro 4 的支持？

请问大佬有计划支持 Surface Pro 4 的触摸屏吗？需要提供什么信息吗？

**Comment by Xiashangning** [comment]
直接用pre-release的版本试一下，应该是可以的

**Comment by Ian-Shu** [comment]
> 才看到本项目已经支持触摸屏了 特地前来膜拜 大佬太强了
> 
> 个人现在正式环境下使用的是本项目的 `v4` 版本，想升级获得触摸屏支持 但触摸屏目前貌似还没有 Surface Pro 4 的支持？
> 
> 请问大佬有计划支持 Surface Pro 4 的触摸屏吗？需要提供什么信息吗？

哥们你成功了吗，surface pro4 i5 8g，你要是成功了我也折腾下

**Comment by kevin-Curry** [comment]
我倒是成功了

**Comment by kevin-Curry** [comment]
> > 才看到本项目已经支持触摸屏了 特地前来膜拜 大佬太强了
> > 个人现在正式环境下使用的是本项目的 `v4` 版本，想升级获得触摸屏支持 但触摸屏目前貌似还没有 Surface Pro 4 的支持？
> > 请问大佬有计划支持 Surface Pro 4 的触摸屏吗？需要提供什么信息吗？
> 
> 哥们你成功了吗，surface pro4 i5 8g，你要是成功了我也折腾下

成功了我倒是
