### ISSUE TITLE
Sleep mode

### ISSUE THREAD

**Issue by MaksimDeve** [Xiashangning/BigSurface#46]
Hello
SP 7 goes into sleep mode? Can this be configured? My screen just turns off the battery keeps draining

**Comment by Xiashangning** [comment]
Nope, sadly even if you correctly configured your config to put sp7 into sleep, the battery will still drain with rate for about 5-10% per hour. That is probably because some hardware has not been put into s3 mode by macOS so they keep consuming power. I can do nothing about that :(
