### ISSUE TITLE
Battery Status on Surface pro 5

### ISSUE THREAD

**Issue by derekkong98** [Xiashangning/BigSurface#49]
Battery status is not showing up, not even batteries settings is showng up on system prefrence. Did I do something wrong? The trackpad is working just fine. Touchscreen is broken on my device anyways so it doesnt matter.
This is my efi: https://drive.google.com/drive/folders/1o3BJ6EexDUBCeV0-Yz-_RJHDCDTTBVhj?usp=sharing
My device is Surface pro 2017 i7-7660U

**Comment by Xiashangning** [comment]
See the updated README (`how to install` section) and check your EFI config

**Comment by derekkong98** [comment]
I dont recall seeing the need to remove the SMCLightSensor.kext and SSDT_ALS0.aml before, but its working just fine now Thanks alot!

**Comment by Xiashangning** [comment]
I have just updated it. My bad
