### ISSUE TITLE
Can't boot with SSDT-SURFACE.aml

### ISSUE THREAD

**Issue by kevin-Curry** [Xiashangning/BigSurface#50]
Surface Laptop 3.
if I add SSDT-SURFACE.aml, it cannot boot.

**Comment by kevin-Curry** [comment]
<img width="768" alt="截屏2022-08-01 22 36 18" src="https://user-images.githubusercontent.com/62877110/182174192-a0bbc592-1e34-401e-bc7d-082b0d0f86b8.png">
And this is my ACPI folder.
I don't know if something make it wrong.

**Comment by kevin-Curry** [comment]
Sorry,actually nothing works. Including keyboard and touchscreen. Using version 6.1

**Comment by kevin-Curry** [comment]
If I add ssdt surface
It cannot even boot

**Comment by Xiashangning** [comment]
I need `sudo dmesg | grep -E "SurfaceS|SurfaceH|SurfaceM|IntelP"`

**Comment by Xiashangning** [comment]
Try this one
[BigSurface.kext.zip](https://github.com/Xiashangning/BigSurface/files/9235657/BigSurface.kext.zip)

PS: AWAC, PNLF-CFL, XOSI are not needed.

**Comment by kevin-Curry** [comment]
> Try this one [BigSurface.kext.zip](https://github.com/Xiashangning/BigSurface/files/9235657/BigSurface.kext.zip)
> 
> PS: AWAC, PNLF-CFL, XOSI are not needed.

Not working.
And no output I added debugenhancer.kext

**Comment by Xiashangning** [comment]
what about ioreg?

**Comment by bitoy81** [comment]
use 6.0. it works fine in monterey including touch. 6.1 dont work on my surface laptop 3.

**Comment by kevin-Curry** [comment]
> use 6.0. it works fine in monterey including touch. 6.1 dont work on my surface laptop 3.

Can you share your efi folder plz

**Comment by Xiashangning** [comment]
[BigSurface.kext.zip](https://github.com/Xiashangning/BigSurface/files/9247532/BigSurface.kext.zip)

**Comment by bitoy81** [comment]
@kevin-Curry i got an i5 10th gen 16gig surface laptop 3 13" i believe you got i7. but here is my config.plist. @Xiashangning im using some of the surface pro 7 from your project can you please check if i need to make changes in the plist especially the device properties. thank you in advance
[config surface laptop3.plist.zip](https://github.com/Xiashangning/BigSurface/files/9247778/config.surface.laptop3.plist.zip)

**Comment by Xiashangning** [comment]
@bitoy81 I’ve sent a new build, plz test it

**Comment by kevin-Curry** [comment]
> @kevin-Curry i got an i5 10th gen 16gig surface laptop 3 13" i believe you got i7. but here is my config.plist. @Xiashangning im using some of the surface pro 7 from your project can you please check if i need to make changes in the plist especially the device properties. thank you in advance
> [config surface laptop3.plist.zip](https://github.com/Xiashangning/BigSurface/files/9247778/config.surface.laptop3.plist.zip)

Could you just send me the whole folder please.

**Comment by Xiashangning** [comment]
> [BigSurface.kext.zip](https://github.com/Xiashangning/BigSurface/files/9247532/BigSurface.kext.zip)

@kevin-Curry @bitoy81 Please test this build, with SSDT-SURFACE

**Comment by ja350exl** [comment]
Does not work on my Surface Book 2 either, on Monterey 12.1 (No effect at all). Tried the version above as well, together with 6.1 and 6.0.

**Comment by Xiashangning** [comment]
this is not helping, I need to understand what is going wrong. not booting? keyboard/touchpad failed to work? battery?
All of these are based on the test build above.
i need sudo dmesg | grep -E 'SurfaceS|SurfaceB|SurfaceM|SurfaceH|IntelP' and the file saved from ioregistryexplorer.app

**Comment by kevin-Curry** [comment]
I can't even boot with it. How can I give you the output?

**Comment by Xiashangning** [comment]
I was speaking to ja350exl for that.
but even with the latest test build above you cannot boot into system?

**Comment by kevin-Curry** [comment]
Yes.

**Comment by ja350exl** [comment]
I'm sorry. sudo dmesg | grep -E 'SurfaceS|SurfaceB|SurfaceM|SurfaceH|IntelP' returns an empty result, none of the features work (no battery icon showing up, volume button not working, etc) - it is as if I did not have the kext installed.
I am unable to upload the IOregistry exported file as the extension is not supported, hence I changed the extension (from .IOREG)
Thanks for the help
[IORegistryExplorer'sOutput.txt](https://github.com/Xiashangning/BigSurface/files/9252691/IORegistryExplorer.sOutput.txt)
.

**Comment by Xiashangning** [comment]
> sudo dmesg | grep -E 'SurfaceS|SurfaceB|SurfaceM|SurfaceH|IntelP' returns an empty result,

@ja350exl That means you have to install DebugEnhancer.kext

**Comment by ja350exl** [comment]
Ok, I will thanks

**Comment by bitoy81** [comment]
@Xiashangning the new test build kext is not working for my surface laptop 3. i even tried both SSDT-SURFACE from 6.0 and 6.1 build. hope new build will still work with surface laptop 3. 6.0 works just fine including touch.

**Comment by ja350exl** [comment]
I cannot boot after adding the kext (DebugEnhancer.kext). I'm stuck here ![image](https://user-images.githubusercontent.com/110546739/182717038-0ad451fd-e158-462c-9305-1fafd249cd19.png)

**Comment by Xiashangning** [comment]
> @Xiashangning the new test build kext is not working for my surface laptop 3. i even tried both SSDT-SURFACE from 6.0 and 6.1 build. hope new build will still work with surface laptop 3. 6.0 works just fine including touch.

Yes, I know. Sorry for the bug. From 6.0 to 6.1 I just tried to integrate support for Surface Laptop 1&2 as well. Something must go wrong during my rewriting.
@kevin-Curry @bitoy81 @ja350exl Try this new build. This one should allow you to boot into the system and give some output. I need output of `sudo dmesg | grep -E "SurfaceS|SurfaceH"`
I have to locate where the bug is first.
[BigSurface.kext.zip](https://github.com/Xiashangning/BigSurface/files/9256391/BigSurface.kext.zip)

PS: for the SSDT, always use the newest one.

**Comment by Xiashangning** [comment]
Update: Try using this build. It is reported to work on another SL3
https://github.com/Xiashangning/IPTSDaemon/files/9256974/BigSurface.kext.zip

**Comment by Xiashangning** [comment]
It is reported to be solved. Plz try this build above. I will leave this here for your response.

**Comment by bitoy81** [comment]
> Update: Try using this build. It is reported to work on another SL3 https://github.com/Xiashangning/IPTSDaemon/files/9256974/BigSurface.kext.zip

@Xiashangning 6.1  build works now. thank you so much. i know there are still work to be done specially on the sleep function. is it normal if i  put my SL3 to sleep to wait around 40 sec for it to sleep and to wake up around 10 sec to fully open? just want to know if its same timeframe for other surface devices.

**Comment by Xiashangning** [comment]
> is it normal if i put my SL3 to sleep to wait around 40 sec for it to sleep and to wake up around 10 sec to fully open

No idea. SP7 seems fine, wake up quite quick. BigSurface has nothing to do with sleep/wakeup so this is likely to be a OC config problem.
