### ISSUE TITLE
Surface Book 3 - Keyboard & Touchpad not working with new kext

### ISSUE THREAD

**Issue by MetalChris87** [Xiashangning/BigSurface#51]
Hi,

I tried the new version 6.1, however I am unable to use the keyboard and touchpad etc. 
I tried to boot with Debug Enhancer kext which I believe you need to help me, however nothing works when I boot with that kext, I cannot even use USB mouse or keyboard.
I was able to save the IORegistry if that helps?

Thanks
[IORegistry.txt](https://github.com/Xiashangning/BigSurface/files/9259338/IORegistry.txt)

**Comment by Xiashangning** [comment]
https://github.com/Xiashangning/IPTSDaemon/files/9256974/BigSurface.kext.zip
Try this test build

**Comment by MetalChris87** [comment]
That works. Perfect. 
Thank you
