### ISSUE TITLE
Request to add Surface Pro 3 Support?

### ISSUE THREAD

**Issue by balopez83** [Xiashangning/BigSurface#54]
Hi @Xiashangning , Is there a chance you will have Surface Pro 3 touchscreen support added to your kext? I have noticed that your kext works amazing for other i2c components on the SP3 but touch isn't yet working properly. 

While I know DSDT/SSDT edits are required unfortunately, I have not been successful in having your kext work yet. Let me know what information you need to integrate this into your kext if you are willing. Thanks in advance.

**Comment by Xiashangning** [comment]
**Surface Pro 3 shouldn't use this kext** as it has no `sam` module as newer models. Your touchscreen is connected via I2C and in fact your whole device behaves just like other normal laptops, (from SP4, MS started to use proprietary hardware to manage battery and so on) I would suggest that you try using VoodooI2C and VoodooI2CHID instead.
