### ISSUE TITLE
Request to add Surface Go 3

### ISSUE THREAD

**Issue by exp13579** [Xiashangning/BigSurface#55]
I have a surface go 3 i3 version with 128gb SSD and 8gb RAM, the UART device id is 9D66. I wonder whether  it will work for my device. Thank you.

**Comment by Xiashangning** [comment]
interesting, i thought go 3 won’t need this. plz send me ioreg saved from ioregistryexplorer.app

**Comment by exp13579** [comment]
Let me find a time to install macOS and I will get you back with the file. Thanks in advance.

**Comment by exp13579** [comment]
[sg3.zip](https://github.com/Xiashangning/BigSurface/files/9334344/sg3.zip)
OK, here you go. Many thanks.

**Comment by Xiashangning** [comment]
Nope, just like other go series, your device is completely a normal laptop. After I examined your ioreg and DSDT, the only thing you need is some DSDT/SSDT modifications.
For example, you already have EC and battery present in your DSDT, just the `_HID` name won't be recognised by macOS
<img width="554" alt="截屏2022-08-19 10 09 58" src="https://user-images.githubusercontent.com/18528518/185574849-b881f9a4-537b-4e8b-b9bf-98af3658ce93.png">
Thus you should consult to the official guide on SSDT and then your battery will be fine.
