### ISSUE TITLE
Mouse clicks randomly whilst I am typing

### ISSUE THREAD

**Issue by MetalChris87** [Xiashangning/BigSurface#56]
On my Surface Book 3 when I am typing anything my touchpad/mouse seems to click itself and this moves the cursor and so when I am typing it moves the cursor to the the middle of the sentence or sometimes it clicks on somewhere else on the screen and this messes me up. When I am typing a sentence it looks something like this "I went for a walk to forest and saw a squirrel the local" so obviously it should have been I went for a walk to the local forest and saw a squirrel but because the mouse cursor clicks itself it messes up my typing. I use the laptop for work and so I constantly have to retype emails. 

Any help would be appreciated. 

Thanks

**Comment by Xiashangning** [comment]
Got it, I will try to add a short silence time for touchpad when typing

**Comment by Xiashangning** [comment]
@MetalChris87 Hi, I am back from school stuff. Sorry for the delay. I've checked the code, well, in fact there already exists a config in BigSurface's Info.plist -> IOKitPersonalities -> Surface Touchpad HID Event Driver -> QuietTimeAfterTyping. The unit is ms so by default it will silence the touchpad for 200ms = 0.2 second after typing event. You can change this to something bigger, like 500 and try to see if it is improved or not.
