### ISSUE TITLE
Do Ambient Light Sensor Work？

### ISSUE THREAD

**Issue by wxxsfxyzm** [Xiashangning/BigSurface#58]
Newly installed Monterey on my SP7, but find no Auto Adjust Brightness in Display Settings, I don't know whether it is a problem from EFI or from BigSurface.kext
![图像](https://user-images.githubusercontent.com/65166044/185748870-f7b54ec8-7b28-45aa-a408-c3f9c6ac8500.jpeg)
.

**Comment by Xiashangning** [comment]
Well, have you installed SSDT-SURFACE ? Also you shouldn't have SMCLightSensor.kext in your config.
If everything is as required, then send me `sudo dmesg | grep "SurfaceA"` with DebugEnhancer.kext enabled

**Comment by wxxsfxyzm** [comment]
efi maintainer BadStorm replied me that he didn't include your newest release. Updating manually solves the problem. Sorry for that.
