### ISSUE TITLE
Surface Pro 4 Keyboard Won't Work After Opening

### ISSUE THREAD

**Issue by balopez83** [Xiashangning/BigSurface#62]
Hi @Xiashangning , I don't know if its a kext issue or something in ACPI but for some reason when I close the keyboard and the computer sleeps when I open the keyboard the computer wakes but no longer accepts input from the Keyboard or trackpad and the keyboard backlight won't light up. Everything else does work, including touch screen, battery, usb devices, etc. 

Sleeping through the menu or power button but not closing the keyboard results in a working keyboard after wake

Also keyboard hot plugging is not working either. 

Do you have any ideas what could be causing this and do you need me to provide additional information?

**Comment by Xiashangning** [comment]
Check the closed issues, someone has already made a similar one. 
I've explained in that issue that sadly I can do nothing about it since BigSurface.kext doesn't manage the power cycle nor the USB part of the TypeCover
