### ISSUE TITLE
大佬你好，s p 7不插电睡眠唤醒后会有强烈的底噪。想请教一下这个问题应该从哪里入手，试着自己生成applealc内核，禁用麦克风也没有效果，不知道问题是在总线还是在intel的cpu省电模式上。

### ISSUE THREAD

**Issue by Rainringgoaway** [Xiashangning/BigSurface#64]

**Comment by Xiashangning** [comment]
这个问题我也很烦，但是我对这方面了解得不多，所以没法给你意见。你可以控制变量尝试看看在哪出的问题。而且只有macOS识别到电池之后才会这样，所以我觉得更可能是mac系统以及applealc驱动的问题，和intel以及DSDT关系不大

**Comment by Rainringgoaway** [comment]
> 这个问题我也很烦，但是我对这方面了解得不多，所以没法给你意见。你可以控制变量尝试看看在哪出的问题。而且只有macOS识别到电池之后才会这样，所以我觉得更可能是mac系统以及applealc驱动的问题，和intel以及DSDT关系不大

我禁用了bigsurface内核后正常了，就是牺牲了触摸手势和光线感应

**Comment by Rainringgoaway** [comment]
多谢大佬指点。有空了再琢磨下
