### ISSUE TITLE
keyboard and touchpad not working after updating surface laptop 3 firmware to the latest version dated 1st Sept 2022

### ISSUE THREAD

**Issue by iloveps4** [Xiashangning/BigSurface#67]
tested using two surface laptop 3, one updated one was still the old firmware.
Very much appreciated if any future updates could get the latest firmware covered.
xiashangning, you are a hero for surface hackintosh, thank you very much.

**Comment by plsh2me** [comment]
@iloveps4 my findings are different from yours -[Here](https://github.com/Xiashangning/BigSurface/issues/61#issuecomment-1242812681) .
Are you sure you have tried on laptop with different bios version?

**Comment by iloveps4** [comment]
@plsh2me  exactly the same issue as mentioned in your link. Below attached are the firmware of my working SL3 and not working SL3 for your information.
![IMG_3978](https://user-images.githubusercontent.com/113851330/191028713-8338e5ee-6ecb-4e8e-9ce5-5ff54fba452c.JPG)
![IMG_3977](https://user-images.githubusercontent.com/113851330/191028703-9f7e4a6b-7e37-4d1c-b0de-e463544f3680.JPG)

**Comment by Xiashangning** [comment]
Please discuss it in #61. I am currently working on this.
