### ISSUE TITLE
Add Realtek USB 3.0 card reader support

### ISSUE THREAD

**Issue by plsh2me** [Xiashangning/BigSurface#7]
I have the Surface pro 7 8gb/128gb version. It have the Realtek USB 3.0 card reader. Can you please add the support for the card reader.
![sdcard](https://user-images.githubusercontent.com/24899438/124354861-20044f80-dc06-11eb-926e-af45558c1e1c.jpg)

If anyone have working kext for this, please share me the kext.
Thank you.

**Comment by jackjack1-su** [comment]
You should ask this question in the community or badstorm's repo. USB problem isn't on the schedule of BigSurface.

**Comment by jackjack1-su** [comment]
Check the PR in badstorm's repo.
