### ISSUE TITLE
Touchpad & Touchscreen on Microsoft Surface Laptop 2

### ISSUE THREAD

**Issue by lzhoang2601** [Xiashangning/BigSurface#73]
I used kext and SSDT-Surface with macOS Monterey

Touchscreen not working. Touchpad works but no gestures

Before that I also had problem getting only touchpad or keyboard at the same time, but changed the patch and they work at the same time

Please help. Thanks

**Comment by Xiashangning** [comment]
Try this one.
[BigSurface.kext.zip](https://github.com/Xiashangning/BigSurface/files/9799852/BigSurface.kext.zip)

PS: touchscreen needs IPTSDaemon to work with.

**Comment by lzhoang2601** [comment]
I tryed but stuck 
![image](https://user-images.githubusercontent.com/50077198/196175720-2b5d8d5f-5780-486e-a0e6-2b385c0997d9.png)
[config.plist.txt](https://github.com/Xiashangning/BigSurface/files/9800367/config.plist.txt)

**Comment by lzhoang2601** [comment]
Solved with disabled SSDT-GPI0. But some time keyboard and touchpad not work. Touchpad does work no gesture

**Comment by lzhoang2601** [comment]
I had to reboot several times to get into macOS. How to solve?

**Comment by lzhoang2601** [comment]
Working perfect with kext in https://github.com/Xiashangning/BigSurface/issues/63#issuecomment-1267831020

**Comment by Xiashangning** [comment]
please try the latest build, either in #63 or above

**Comment by Xiashangning** [comment]
This one
[BigSurface.kext.zip](https://github.com/Xiashangning/BigSurface/files/9801375/BigSurface.kext.zip)

**Comment by lzhoang2601** [comment]
Installed IPTSDaemon but touchscreen not working

**Comment by Xiashangning** [comment]
do you follow the installation instructions?
And does this build above work for you

**Comment by lzhoang2601** [comment]
> This one [BigSurface.kext.zip](https://github.com/Xiashangning/BigSurface/files/9801375/BigSurface.kext.zip)

I can't start macOS with kext

P/s: Sorry, i forget install fmt and inih for touchscreen work

**Comment by lzhoang2601** [comment]
> Working perfect with kext in [#63 (comment)](https://github.com/Xiashangning/BigSurface/issues/63#issuecomment-1267831020)

I always have to boot up twice to get the keyboard to work

**Comment by Xiashangning** [comment]
> 

Upgrade Lilu & VirtualSMC to the latest version. Try again.

**Comment by lzhoang2601** [comment]
I used last commit for all kext

**Comment by Xiashangning** [comment]
What about this ?
You won't need BrightnessKeys.kext btw.
[BigSurface.kext.zip](https://github.com/Xiashangning/BigSurface/files/9803797/BigSurface.kext.zip)

**Comment by Xiashangning** [comment]
Another SL1 user in #63 report it working without bugs, since SL1 and SL2 are very similar, and my kext treats SL1 & 2 identically, please recheck your OC config
