### ISSUE TITLE
Battery status on Microsoft Surface Book

### ISSUE THREAD

**Issue by lzhoang2601** [Xiashangning/BigSurface#74]
I used kext and SSDT-Surface with macOS Monterey. But battery status is not working, what do I need to do to make it work?

Thanks.

**Comment by Xiashangning** [comment]
I need logs `sudo dmesg | grep -E "SurfaceS|SurfaceB"`

**Comment by lzhoang2601** [comment]
[SSDT.zip](https://github.com/Xiashangning/BigSurface/files/9840588/SSDT.zip)
[config.plist.txt](https://github.com/Xiashangning/BigSurface/files/9840594/config.plist.txt)

I used two patches and kext ACPIBatteryManager. Battery status and sound button worked

**Comment by lzhoang2601** [comment]
> I need logs `sudo dmesg | grep -E "SurfaceS|SurfaceB"`

Nothing show in terminal, DebugEnhancer loaded

**Comment by Xiashangning** [comment]
I have checked Surface Book's DSDT, it does not use the surface aggregator module so there is no need to use BigSurface.kext at all.
