### ISSUE TITLE
Version 6.2 breaks Trackpad / Battery / Volume Keys

### ISSUE THREAD

**Issue by backdash756** [Xiashangning/BigSurface#75]
Hi, 

when I update to version 6.2 or 6.3, my trackpad is no longer recognized as a Magic trackpad. It only works as a mouse.
Also battery indicator and volume key's are no longer recognized.
If I then downgrade version 6.0 again it still doesn't work, I have to restore the whole EFI folder where version 6.0 was in.

**Comment by Xiashangning** [comment]
What device

**Comment by backdash756** [comment]
Sorry, I forgot: Surface Pro 7

**Comment by Xiashangning** [comment]
That's impossible, it's your oc config's problem. I am using a SP7 so SP7 will be guaranteed to work

**Comment by Xiashangning** [comment]
attach your config.plist here

**Comment by backdash756** [comment]
What can be responsible for that? I really don't change ANYTHING except BigSurface.kext and SSDT-Surface.aml.
Strange, as i said, it remains broken even if i go back to 6.0.
If I restore the EFI folder from the backup, everything works again.
Here is my config.plist
[config.plist.zip](https://github.com/Xiashangning/BigSurface/files/9868886/config.plist.zip)

**Comment by Xiashangning** [comment]
Have you upgraded Lilu and VirtualSMC to the latest version?

**Comment by backdash756** [comment]
Yes, Lilu 1.6.3 and VirtualSMC 1.3.1

**Comment by Xiashangning** [comment]
please read the README, the loading sequence is not right

**Comment by backdash756** [comment]
You're right, it was the loading sequence. It works now. This also explains why it didn't work again after the downgrade, oc auxiliary tools sorted by name when pasting the kext again.
Many thanks for the help
