### ISSUE TITLE
Support older version of macOS

### ISSUE THREAD

**Issue by pigworlds** [Xiashangning/BigSurface#76]
First big thank you for this great work! Without BigSurface.kext I won't able to use keyboard on SL1.

I tried BigSurface.kext on Mojave, it doesn't seems to work. Further look show that BigSurface.kext only run on macOS 10.15+.

Getting support on older version of OS isn't complicated. You just need to set MACOSX_DEPLOYMENT_TARGET to lower version, and fix another one line code to let the kext compatible with older OS.

I have created a diff https://github.com/Xiashangning/BigSurface/compare/dev...pigworlds:BigSurface:downlevel and verified working well from Sierra and above. Choosing Sierra as the baseline because it is the oldest OS that can run on SL1. In addition to this diff, the similar MACOSX_DEPLOYMENT_TARGET change need apply to all three submodules too.

Would you mind incorporate this to support older version of macOS?

**Comment by Xiashangning** [comment]
To be honest, I cannot understand why someone would prefer an older version of OS. Unless you give me a good enough reason, I am not going to add support for 10.14 and older.

**Comment by Xiashangning** [comment]
PS: since you have a SL1, may I ask you to test if your caps lock led is turned on correctly?

**Comment by RockJesus** [comment]
> 

我的是sl1用了你最新的版本，大写键可以使用，但是led不会亮，这个功能倒是无所谓，需要的话我可以帮你测试，QQ 2994638

**Comment by pigworlds** [comment]
Adding older OS support gives people the choices of the OS that works best. I’m always running the latest OS on the bleeding edge, but not all people would do. Just like you add Catalina support a while ago, I would appreciate lower level of OS to be supported.

**Comment by pigworlds** [comment]
> PS: since you have a SL1, may I ask you to test if your caps lock led is turned on correctly?

The Caps lock functionality works fine. But the Caps lock led keeps off.

There are minor stability issues on SL1 keyboard. The keyboard won’t work immediate after the boot. I usually need to wait a few seconds on the login window before I can type the password. There is also chances the keyboard won’t get detected at all.
I can see some stability improvements in version 6.3, and still there are times I need to reboot the laptop.

**Comment by Xiashangning** [comment]
Fine, even though it is against my will, I will adjust the OS support down to Serria in next release. :)
For now, you can only try to build it yourself.
