### ISSUE TITLE
Surface laptop 1 trackpad

### ISSUE THREAD

**Issue by SmartBoy84** [Xiashangning/BigSurface#77]
Before trackpad wouldn't work on some boots but that was usually fixed by a reboot
However now it doesn't work no matter how many times I boot

**Comment by SmartBoy84** [comment]
Turns out I wasn't usually the release version, works fine now!

**Comment by MeisterLone** [comment]
@SmartBoy84 could you possibly provide working EFI for SL1? 

I can not get mine to work using current instructions.
