### ISSUE TITLE
关于Surface Pro 6触屏的问题

### ISSUE THREAD

**Issue by 123MEMZ** [Xiashangning/BigSurface#80]
两位作者大大，我想来咨询关于SP6触屏的问题。我已下载并安装上您那个"BigSurface"，可是我遇到了一个很奇怪的问题，我无法使用触摸屏，但是电源显示以及按钮都是正常的，所以我就想来咨询一下，希望能解决这个问题。

我已经尝试把"BigSurface"的版本从6.3降级到6.2，但还是毫无效果qwq，我将把我的设置截图放上来，如果还有什么我需要提供的截图，请尽管说，我将会一一放上来！

辛苦了！～

_（哦对，还有个问题，我怎么才能启用环境光？是只能自己编写驱动了吗？）_

<img width="1368" alt="截屏2022-11-24 上午3 15 27" src="https://user-images.githubusercontent.com/97831256/203629640-5c81349d-1c89-409e-97e3-f337489bbd1c.png">
<img width="1368" alt="截屏2022-11-24 上午3 16 03" src="https://user-images.githubusercontent.com/97831256/203629676-94f7e71d-d391-45e1-bcf7-9ae94b732775.png">
<img width="1368" alt="截屏2022-11-24 上午3 16 20" src="https://user-images.githubusercontent.com/97831256/203629693-2a5ca8cf-1d27-4620-9250-453ab7351931.png">

**Comment by Xiashangning** [comment]
环境光：是的，只能你自己写

你需要发给我终端`sudo dmesg | grep -E "SurfaceM|IntelP"` 的输出，同时记得把DebugEnhancer.kext启用
然后你双击IPTSDaemon那个可执行文件，把他的输出截图给我

**Comment by Xiashangning** [comment]
还有，请永远使用最新版的驱动

**Comment by 123MEMZ** [comment]
这是终端截图

<img width="697" alt="截屏2022-11-24 下午7 18 49" src="https://user-images.githubusercontent.com/97831256/203773250-e0af77f2-7d97-4283-a51a-10cecdb65626.png">



我很抱歉没有找到DebugEnhancer.kext和IPTSDaemon这个执行文件，还请大佬能够指点一下我～

**Comment by Xiashangning** [comment]
额，那是因为还要下载IPTSDaemon才能用触摸屏。是我的另一个项目，那里有开启触摸屏的详细教程

**Comment by 123MEMZ** [comment]
这是IPTSDaemon的输出截图，请查收！
<img width="697" alt="截屏2022-11-26 下午4 05 42" src="https://user-images.githubusercontent.com/97831256/204078883-637ab857-4c9c-41af-9cdc-629181f5edc4.png">

**Comment by 123MEMZ** [comment]
我看您这个项目的介绍说是只有macOS 12及以上的版本才需要安装DebugEnhancer.kext吧，我是macOS 11

**Comment by Xiashangning** [comment]
请仔细看IPTSDaemon的安装说明，按要求来

**Comment by 123MEMZ** [comment]
我按照您的项目一步步走下去之后会提示这个

<img width="697" alt="截屏2022-11-26 下午6 58 11" src="https://user-images.githubusercontent.com/97831256/204085398-af97f67c-a386-48e5-96dd-611c2b0dadd8.png">

**Comment by 123MEMZ** [comment]
我不知是正常的还是出了点问题

**Comment by 123MEMZ** [comment]
然后运行install_daemon.sh后终端无任何输出，但重启依旧没有触控

**Comment by 123MEMZ** [comment]
<img width="690" alt="截屏2022-11-27 上午3 23 40" src="https://user-images.githubusercontent.com/97831256/204105754-09f6eabd-0d96-4abe-8fed-9ffa6e1a0f00.png">
