### ISSUE TITLE
SP5 (SP 2017) Surface no longer booting

### ISSUE THREAD

**Issue by m1nt24** [Xiashangning/BigSurface#83]
Hi!
I hope you are well. 
I found out about BigSurface and I was quite happy to actually install it into my EFI. It is now longer booting and the screen is stuck on some text in verbose. So I went back to my old efi. 

Everything on my old EFI was working except battery was on 100 and not charging. 
Where is it possible to send the EFI to check? Thank you!

My EFI is from this link: https://github.com/MrHomebrew/Surface-Pro-2017-OpenCore-EFI

edit: I followed all the steps, but I didnt delete VirtualSMC as I wasnt required to delete it?

Will

**Comment by Xiashangning** [comment]
> I followed all the steps, but I didnt delete VirtualSMC

You have to keep VirtualSMC but delete ALL its plugins (SMCLightSensor etc.)

**Comment by Xiashangning** [comment]
And with SSDT-Surface.aml
