### ISSUE TITLE
No keyboard/trackpad on Surface Pro 4 (SP4)

### ISSUE THREAD

**Issue by yummytutel** [Xiashangning/BigSurface#85]
The type cover isnt working nor lighting up when booting to the mac os installer and i can't seem to find a solution for this even while using the voodooi2c kext over bigsurface

**Comment by Xiashangning** [comment]
At least the typecover will be recoginsed as a USB connected touchpad with basic functions. If it isn;t working, then unfortunately I can do nothing about it. Only with macOS recognising it can BigSurface be useful.
