### ISSUE TITLE
你好，在使用bigsurface过程中遇到问题

### ISSUE THREAD

**Issue by LuxferreX** [Xiashangning/BigSurface#86]
首先感谢辛勤付出！

现在遇到如下问题，如果能百忙之中抽出时间给予答疑解惑，不胜感激！

设备为surface book 2，i5 7300u版本

1.光纤传感器未正常工作，并未加入SMCLightSensor.kext。在加载DebugEnhancer.kext后，运行sudo dmesg | grep "SurfaceA"并无输出结果。

2.升级到Ventura 后，关机变为重启，重启后有IOHIDFamily（2.0）报错，替换后发现是VoodooI2C的插件引起的，因此期待新的适配。

年关将近，万望注意身体，感谢有你！

**Comment by LuxferreX** [comment]
另外，还有两件事情请教。
就是-v跑马的时候，发现bigsurface很多地方跑马响应有点慢，是否有办法加速，以便提升开机速度？
还有就是通过导入证书隐藏开机 红锁的方法能否适用于sb2？我尝试了一下，似乎无法成功引导，虚心求教！

**Comment by Xiashangning** [comment]
光线传感器只能在SP7和SL3上用，其他型号的硬件不一样没法用。只能你自己写驱动
-v跑码那个不是bigsurface慢，是系统在启动。用release版本就行了
导入证书可以用。按照教程来就行

**Comment by LuxferreX** [comment]
> 光线传感器只能在SP7和SL3上用，其他型号的硬件不一样没法用。只能你自己写驱动 -v跑码那个不是bigsurface慢，是系统在启动。用release版本就行了 导入证书可以用。按照教程来就行

收到来信，感谢解答！祝诸事顺意，大吉大利！
