### ISSUE TITLE
surfacepro7插入音响有沙沙声

### ISSUE THREAD

**Issue by 1576495283** [Xiashangning/BigSurface#89]
surfacepro7最新驱动黑苹果了，插入音响依然有沙沙声，而且不能使用外接显示器音频（不能使用显卡音频）

**Comment by 1576495283** [comment]
盒盖后再次打开，喇叭发出很大的沙沙声，每次都是如此。需要重新调整下音量后消失； 希哈值报错依然存在；触摸屏不灵敏或者过于灵敏而且特别费电.

**Comment by Xiashangning** [comment]
> 插入音响依然有沙沙声，而且不能使用外接显示器音频

无解，或者你可以研究研究咋解决

> 盒盖后再次打开，喇叭发出很大的沙沙声

没办法，只要驱动了电池，插着电源就会这样

> 希哈值报错

这个和我一点关系都没。。。大哥这个是Opencore或者是mac的问题


> 触摸屏不灵敏或者过于灵敏而且特别费电.

费电是真的，不过你不碰屏幕还好。触摸屏我在改代码，到时候会给你们选择，单指触摸还是多指，多指非常耗电。

**Comment by 1576495283** [comment]
好的，谢谢

**Comment by Rainringgoaway** [comment]
> > 希哈值报错
> 
> 这个和我一点关系都没。。。大哥这个是Opencore或者是mac的问题

这个问题可以去驱动开发者issue频道自寻，他写了一版intelBTpatch.kext，可以解决希哈错误，蓝牙也可更稳定，不会出现唤醒后蓝牙无法使用，但是有新bug，会掉定位。
