### ISSUE TITLE
Trackpad not working properly on 10.15.7

### ISSUE THREAD

**Issue by emiyl** [Xiashangning/BigSurface#9]
Running with OpenCore on 10.15.7 with BigSurface on a Surface Pro 6.

+ Trackpad is usable as a mouse and can scroll, however clicking on things doesn't work as expected (clicking a folder in Finder doesn't open it, but displays information about the folder)
+ In System Preferences, under Trackpad, it shows "No trackpad"

**Comment by Xiashangning** [comment]
You should configure your trackpad to get these functions work
You can try these commands(Remember to execute them one by one)
> // This configuration works for me, but someone make it work removing sudo
sudo defaults write NSGlobalDomain com.apple.trackpad.forceClick -bool false
sudo defaults write com.apple.AppleMultitouchTrackpad ForceSuppressed -bool true
sudo defaults write com.apple.AppleMultitouchTrackpad ActuateDetents -bool false
sudo defaults write com.apple.AppleMultitouchTrackpad Clicking -bool true 
sudo defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad Clicking -bool true 
sudo defaults -currentHost write NSGlobalDomain com.apple.mouse.tapBehavior -int 1 
sudo defaults write NSGlobalDomain com.apple.mouse.tapBehavior -int 1
sudo defaults write com.apple.AppleMultitouchTrackpad Dragging -bool true 
sudo defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad Dragging -bool true

and then reboot.

**Comment by emiyl** [comment]
Thank you, all trackpad functionality now works fine.
