### ISSUE TITLE
Surface Pro 5 (2017) frozen after boot 

### ISSUE THREAD

**Issue by MauriceChocoSwiss** [Xiashangning/BigSurface#90]
Hi, I've a trouble with my SP5 with Monterey (Same problem append with Mojave...). After the install, when it start, it froze on language select page, sometime juste after.

I've seen on openCore page that i need to use CPUTsc but I don't know if i need to use it or no with BigSurface.
I've tested with minimal configuration (Just VirtualSMC and Lilu and some SSDT recommended for Kaby Lake Laptop) but nothing work.
I've removed all SMC plugins too.

What did you need to help with this ?

SP5, I7-4660U, 46Gb, 1Tb.

**Comment by Xiashangning** [comment]
I can't. BigSurface is a driver to improve the using experience of Surface devices on macOS. If you cannot even boot into the system, I am afraid nothing I can do. You should first try to boot into macOS without any problem (disable BigSurface, enable VoodooI2C, VirtualSMC etc.). Then, you can enable BigSurface for full support of the battery etc.

**Comment by Xiashangning** [comment]
BTW BigSurface has no conflict with CPUTsc

**Comment by MauriceChocoSwiss** [comment]
I've finished the installation, I've used antoher EFI i found, with your kext inside and i don't know really why, it work this time.

Thank's for the infomartions ;)
