### ISSUE TITLE
version 6.5

### ISSUE THREAD

**Issue by kevin-Curry** [Xiashangning/BigSurface#92]
In IPTSDaemon. Version 1.4 is working with 6.5?
![image](https://user-images.githubusercontent.com/62877110/221386707-cf78278c-4761-45d3-bdb9-6caeb9eb5135.png)

**Comment by Xiashangning** [comment]
Yeah, but for BigSurface there is still a "small" bug needed to be solved for the release. I thought it was quick but it turned out to be quite delicate.

**Comment by Xiashangning** [comment]
6.5 released
