### ISSUE TITLE
Battery not recognised in System Preference in Ventura

### ISSUE THREAD

**Issue by Xiashangning** [Xiashangning/BigSurface#93]
In Ventura, without any changes made to the battery code, the battery failed to be recognised in System Preference.

However, macOS does seem to know that there is a battery present as it can show it correctly in the control center or menu bar.

**Comment by Xiashangning** [comment]
Don't know if normal laptop has this issue in Ventura or not. The battery code is almost exactly the same from SMCBatteryManager.

**Comment by he1833** [comment]
Ordinary notebooks also have this problem, although I don't have ordinary books, I saw the same case of oil and our problem in the Vision Forum, and the general solution seems to be compiled with the latest ECEnabler.kext to resolve

**Comment by Xiashangning** [comment]
Thanks for your advice but ECEnabler won't help

**Comment by he1833** [comment]
I succeeded and found a workaround by modifying the error identification in the FACP table in the form of an APCI patch so that he correctly identified the Surface as a laptop. Without patching, it is identified as the type of tablet, and it will not correctly match the battery (for laptops) or energy saving (for desktops) in the settings.

**Comment by he1833** [comment]
![1679790109557](https://user-images.githubusercontent.com/127579787/227748743-f94c906d-c831-408b-bdb4-c1b59180d4ea.jpg)

**Comment by Xiashangning** [comment]
Yes, this patch works for me!

Thanks a lot, I will add it into the readme

**Comment by olekor** [comment]
Could you give me advice about the installation IPTSDaemon (Monterey 12.4, surface book 2 13" i5 7300u) When running install_daemon.sh  I have this picture
![Снимок экрана 2023-05-08 в 11 05 24](https://user-images.githubusercontent.com/20501766/236812104-ebd0f917-26c9-446b-93fa-0b0a26d55cf9.jpg)

as I suppose to install a daemon.sh need to use Homebrew, but at the present time, I don't have a USB WIFI dongle to connect internet, as for Marvell AVASTAR wifi card doesn't have a kext.
I tried to install the daemon manually but also had no success. I would be very grateful for your advice.

**Comment by LvxlongSir** [comment]
try MacBook Air. sb shared sp7 with this model and it's okay with battary on ventura.
