### ISSUE TITLE
Best Compatible Surface

### ISSUE THREAD

**Issue by rkinlen** [Xiashangning/BigSurface#94]
I switch from a desktop Hackintosh to a laptop Hackintosh. Does anyone know the best surface model to be used with this?

**Comment by plsh2me** [comment]
For me Microsoft Surface Laptop 3 15inch is the best one - https://www.ebay.co.uk/itm/394482658879?mkcid=16&mkevt=1&mkrid=711-127632-2357-0&ssspo=_vqbygs5sey&sssrc=2349624&ssuid=_vqbygs5sey&var=&widget_ver=artemis&media=WHATS_APP

https://www.ebay.co.uk/itm/404180900494?hash=item5e1b0f1a8e:g:DwcAAOSwv1Zj~SLF&amdata=enc%3AAQAHAAAAsA0UC01IJeJS9%2FGq9FcKa4QzBE4PexA1NjyzvVjP5YBHTtRnrZJAvSHVdTgCyOYatnyJp5efL22qcwZv3xKoo2qZ6Y9b3nBtbT4fzph2zjkU2a1291jzk1RBlgW649hxSBrioCXreRcnf%2B%2FZ6%2FLLpeTzczUhJdKKiLvhqGMvb5shwxJjZB%2B6B%2BGp%2FfTFB1zCRsLBV9E3Dlcys2hrUy5nDmvEGmyYkhVAa7XyKudKbD5v%7Ctkp%3ABk9SR_qNk43XYQ

**Comment by rkinlen** [comment]
would this work? https://www.microsoft.com/en-gb/store/configure/Surface-Laptop-Go-2/8pglpv76mjhn?icid=PDP_LaptopGo2_CTA1

**Comment by rkinlen** [comment]
> For me Microsoft Surface Laptop 3 15inch is the best one - https://www.ebay.co.uk/itm/394482658879?mkcid=16&mkevt=1&mkrid=711-127632-2357-0&ssspo=_vqbygs5sey&sssrc=2349624&ssuid=_vqbygs5sey&var=&widget_ver=artemis&media=WHATS_APP
> 
> https://www.ebay.co.uk/itm/404180900494?hash=item5e1b0f1a8e:g:DwcAAOSwv1Zj~SLF&amdata=enc%3AAQAHAAAAsA0UC01IJeJS9%2FGq9FcKa4QzBE4PexA1NjyzvVjP5YBHTtRnrZJAvSHVdTgCyOYatnyJp5efL22qcwZv3xKoo2qZ6Y9b3nBtbT4fzph2zjkU2a1291jzk1RBlgW649hxSBrioCXreRcnf%2B%2FZ6%2FLLpeTzczUhJdKKiLvhqGMvb5shwxJjZB%2B6B%2BGp%2FfTFB1zCRsLBV9E3Dlcys2hrUy5nDmvEGmyYkhVAa7XyKudKbD5v%7Ctkp%3ABk9SR_qNk43XYQ

would this work? https://www.microsoft.com/en-gb/store/configure/Surface-Laptop-Go-2/8pglpv76mjhn?icid=PDP_LaptopGo2_CTA1
