### ISSUE TITLE
Surface Pro 7 Ventura no touchscreen 

### ISSUE THREAD

**Issue by sonvirgo** [Xiashangning/BigSurface#95]
[dsdt.aml.zip](https://github.com/Xiashangning/BigSurface/files/10950654/dsdt.aml.zip)
[ioreg.zip](https://github.com/Xiashangning/BigSurface/files/10950655/ioreg.zip)
![Screen Shot 2023-03-12 at 1 32 10 PM](https://user-images.githubusercontent.com/10823037/224540846-543fe95a-e677-429c-953c-9d21c73443ea.png)

**Comment by Xiashangning** [comment]
Ur problem is most likely because u didn't update the loading config for BigSurface (there is a new plugin)
