### ISSUE TITLE
Stuck when Boot Surface Laptop 3

### ISSUE THREAD

**Issue by andreszerocross** [Xiashangning/BigSurface#96]
I just stuck here when Using BigSurface.kext, after research try and error i know the problem is "VoodooSerial.kext". When i disabled this kext, it can boot but no battery, keyboard and touchpad.

Currently i am using Ventura with OpenCore 0.9.0

![WhatsApp Image 2023-03-22 at 21 30 24](https://user-images.githubusercontent.com/9614101/226946376-894a1c3e-48de-4f17-af90-20797e2d8fcb.jpeg)

**Comment by Xiashangning** [comment]
Have you added Surface-SSDT?

**Comment by andreszerocross** [comment]
Yes, i already add it. In IOREG when i disable VoodooSerial.kext i can see "ALS0, ADP0, BAT0 and IPTS". When 4 of these device is shown then it mean SSDT is loaded, right??

**Comment by andreszerocross** [comment]
![image](https://user-images.githubusercontent.com/9614101/226955369-b0acea56-2538-4c86-9b4f-092711170593.png)


I don't know if this picture will help, but this is the version all controller firmware

**Comment by Xiashangning** [comment]
It is strange. Usually VoodooSerial will not have this kind of problem. What I can see that is abnormal is the duplicated line for VoodooUART at the bottom... There should only be one line, maybe this indicates VoodooSerial is being loaded twice?
I do have a lot of SL3 users, yet they report no issue like this. Can you attach your IOReg? (without BigSurface being loaded)

**Comment by andreszerocross** [comment]
[HIN’s MacBook Pro.ioreg.zip](https://github.com/Xiashangning/BigSurface/files/11071249/HIN.s.MacBook.Pro.ioreg.zip)

Here is the ioreg output without "BigSurface.kext and plugin"

**Comment by Xiashangning** [comment]
I need your OC config

**Comment by andreszerocross** [comment]
[EFI.zip](https://github.com/Xiashangning/BigSurface/files/11072711/EFI.zip)


Here it's

**Comment by andreszerocross** [comment]
> I need your OC config

Any info yet? Is it related to firmware of the notebook or hardware?

**Comment by Xiashangning** [comment]
Delete ECEnabler, CpuTscSync, RestrictEvents and try again

**Comment by Xiashangning** [comment]
Also, XOSI is not needed.
Personally speaking, its your config's problem, not BigSurface's

**Comment by andreszerocross** [comment]
Do you have any SL3 user use BigSurface.kext in Ventura?? Maybe link repository of them?

**Comment by andreszerocross** [comment]
> Also, XOSI is not needed.
> Personally speaking, its your config's problem, not BigSurface's

If XOSI or darwin for Windows 10 is not applied then you will see about lot of failure GPIO match from I2C or serial controll in logs

**Comment by andreszerocross** [comment]
> Delete ECEnabler, CpuTscSync, RestrictEvents and try again

AFAI, i have tried disable ECEnabler, CPUTSC and RestrictEvent, IntelBluetooth, IntelBTPatcher, itlwm and CPUFriend but it always stuck if i enable plugin of BigSurface.kext (VoodooSerial)  . I have tried only enable VITAL kext like Lilu, VirtualSMC, WhateverGreen

**Comment by Xiashangning** [comment]
It is really weird...
There are some working configs for SL3 on github. Like this one https://github.com/WhyToFly/SurfaceLaptop3-OpenCore
So that is why I think that the problem is not from BigSurface's part.
