### ISSUE TITLE
Is Surface Go 2 supported?

### ISSUE THREAD

**Issue by SoftwareRat** [Xiashangning/BigSurface#98]

**Comment by Xiashangning** [comment]
Surface Go 2 doesn't need this.

**Comment by SoftwareRat** [comment]
No, there is no good tutorial to do this on Surface Go 2

**Comment by jlempen** [comment]
@SoftwareRat Actually, there is my [tutorial for the Surface Go 2](https://github.com/jlempen/Surface-Go-2-OpenCore).
Almost eerything is working on the Core m3 Go 2, apart from the cameras and sleep. Hibernation is supported, though. It's a cool little hackintosh tablet!
